'use client';
import {useEffect,useState} from 'react';
import {LanguageSwitch,useLanguage} from '@/components/language';
import {flushSync} from 'react-dom';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Checkbox} from '@/components/ui/checkbox';
import {people,meetings,timestamps} from '@/lib/scenario';
import {initialState,restore,act,extract,recall,type State,type MemoryId,type Answer,type Memory} from '@/lib/memory';
import {confirmInPlace,saveAndExtract} from '@/lib/workflow';
import {ArrowUpRight,ArrowUp,Plus,Check,FileText,MessageSquare,ChevronRight,BookOpen,History,Mic} from 'lucide-react';
const KEY='zhixu-ibs-memory-v3';
type Panel='memory'|'history'|'source'|'record'|null;
export default function Home(){
 const {language,switchLanguage,t,localize}=useLanguage();
 const [state,setState]=useState<State>(initialState),[ready,setReady]=useState(false),[storage,setStorage]=useState('读取本机记忆…');
 const [view,setView]=useState('assistant'),[actor,setActor]=useState('Han'),[sessionId,setSessionId]=useState(''),[question,setQuestion]=useState(''),[ignore,setIgnore]=useState<MemoryId[]>([]);
 const [panel,setPanel]=useState<Panel>(null),[selected,setSelected]=useState<MemoryId>('data'),[sourceMeeting,setSourceMeeting]=useState(2),[sourceSpeaker,setSourceSpeaker]=useState(3),[meeting,setMeeting]=useState(2);
 const [editing,setEditing]=useState(false),[editText,setEditText]=useState(''),[notice,setNotice]=useState(''),[reviewOpen,setReviewOpen]=useState(false);
 const [mode,setMode]=useState('线下'),[video,setVideo]=useState('仅音频'),[consent,setConsent]=useState(false),[recording,setRecording]=useState(false),[speaker,setSpeaker]=useState('待确认');
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setState(restore(raw));setStorage('本机记忆已载入')}catch{setNotice('本机存档无法读取，已载入预置场景。');setStorage('本机存档读取失败')}setReady(true)},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(KEY,JSON.stringify(state));setStorage('已保存到本机')}catch{setStorage('保存失败，仅当前页面有效');setNotice('本机存储不可用，关闭页面后可能丢失变更。')}},[state,ready]);
 useEffect(()=>{const listener=(e:StorageEvent)=>{if(e.key!==KEY||!e.newValue)return;try{setState(restore(e.newValue));setNotice('其他标签页更新了记忆，当前页面已同步。')}catch{setNotice('其他标签页的存档无法读取。')}};window.addEventListener('storage',listener);return()=>window.removeEventListener('storage',listener)},[]);
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>unknown}}).modelContext;if(!ctx)return;const c=new AbortController();try{Promise.resolve(ctx.registerTool({name:'navigate_research_workspace',description:'打开研究助手或会议记录；旧页面名称映射到原地面板，不更改记忆。',inputSchema:{type:'object',properties:{page:{type:'string',enum:['assistant','meetings','home','review','memory','chat','progress']}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const d=input as {page?:unknown};if(!d||Object.keys(d).length!==1||!['assistant','meetings','home','review','memory','chat','progress'].includes(String(d.page)))throw new Error('无效页面');flushSync(()=>{setView(d.page==='meetings'?'meetings':'assistant');if(d.page==='memory')setPanel('memory');if(d.page==='review')setReviewOpen(true)});return {page:d.page}}},{signal:c.signal})).catch(()=>{});}catch{}return()=>c.abort()},[]);
 const current=state.sessions.find(s=>s.id===sessionId&&s.actor===actor);
 const answer=current?.answer;
 const data=state.memories.find(m=>m.id==='data')!;
 const pending=state.memories.filter(m=>m.project==='M09'&&m.status==='pending'&&(m.scope==='team'||m.owner===actor));
 const names={pending:'待确认',confirmed:'有效',rejected:'不保存',forgotten:'已忘记'};
 function switchActor(name:string){setActor(name);setSessionId('');setQuestion('');setIgnore([]);setNotice(`已切换到 ${name} 的演示视角；现在可以就地核查。`)}
 function commit(next:State,message:string){const active=next.sessions.find(s=>s.id===sessionId&&s.actor===actor);if(active?.answer)next={...next,sessions:next.sessions.map(s=>s.id===sessionId?{...s,answer:recall(next,actor,s.question,ignore)}:s)};setState(next);setNotice(message)}
 function run(fn:(s:State)=>State,message:string){try{commit(fn(state),message)}catch(e){setNotice((e as Error).message)}}
 function source(id:MemoryId,m?:number,p?:number){const record=state.memories.find(x=>x.id===id)!;setSelected(id);setSourceMeeting(m??record.meeting);setSourceSpeaker(p??record.speaker);setEditing(false);setPanel('source')}
 function ask(q=question,ids=ignore){if(!q.trim())return;const id=current?.id??crypto.randomUUID();const reply=recall(state,actor,q,ids);setState(s=>({...s,sessions:current?s.sessions.map(c=>c.id===id?{...c,question:q.trim(),answer:reply}:c):[...s.sessions,{id,actor,question:q.trim(),answer:reply}]}));setSessionId(id);setQuestion('');setView('assistant')}
 function newChat(){setSessionId('');setQuestion('');setIgnore([]);setView('assistant');setNotice('新会话已就绪，项目记忆保留。')}
 function toggle(id:MemoryId){const next=ignore.includes(id)?ignore.filter(i=>i!==id):[...ignore,id];setIgnore(next);if(current?.answer)ask(current.question,next);setNotice(next.includes(id)?'已排除此记忆，并更新回答。':'已恢复此记忆，并更新回答。')}
 function download(a:Answer){const blob=new Blob([`# ${t(current?.question??'研究摘要')}\n\n${t('IBS 虚构场景 · 规则演示')}\n\n${t(a.text)}\n\n${t('依据：')}\n${a.used.map(m=>`${t(m.title)}: ${t(m.source)}`).join('\n')}`],{type:'text/markdown;charset=utf-8'});const url=URL.createObjectURL(blob);const el=document.createElement('a');el.href=url;el.download=language==='en'?'Zhixu-research-summary.md':'知序-研究摘要.md';el.click();URL.revokeObjectURL(url)}
 function actionButtons(m:Memory){return <div className="compact-actions">{m.status==='pending'&&<>{m.owner!==actor?<Button variant="outline" onClick={()=>switchActor(m.owner)}>切换到 {m.owner} 核查</Button>:<Button disabled={m.id==='data'&&(state.sourceDirty||!m.value)} onClick={()=>run(s=>confirmInPlace(s,m.id,actor),'已核查确认；后续回答使用当前版本。')}>{m.id==='data'?'核对无误，确认数据':'确认这项决策'}</Button>}<button className="quiet-button" onClick={()=>run(s=>act(s,m.id,'reject',actor),'已选择不保存。')}>不保存</button></>}{m.status==='rejected'&&m.owner===actor&&<Button variant="outline" onClick={()=>run(s=>act(s,m.id,'reconsider',actor),'已重新进入待确认。')}>重新核查</Button>}{m.status==='confirmed'&&m.owner===actor&&<button className="quiet-button" onClick={()=>run(s=>act(s,m.id,'forget',actor),'已忘记项目记忆，后续不再调用；原会议保留。')}>忘记这条记忆</button>}{m.id==='data'&&(m.status==='forgotten'||state.sourceDirty)&&<Button variant="outline" onClick={()=>run(s=>extract(s,actor),'已从原文提取候选，等待 Choi 确认。')}>从原文重新提取</Button>}</div>}
 function reviewCard(m:Memory){return <div className="inline-review" key={m.id}><div className="review-label"><span className="dot"/><strong>{m.id==='data'?'数据修订':'阶段决策'}</strong><span>{m.owner} 负责</span></div><h3>{m.id==='data'?(m.value?`B 组接触电阻：${m.value} Ω·μm`:'原文已修改，等待提取'):'两组良率至少 75% · 09.23 起'}</h3><p>{m.id==='data'?'A 组 820 Ω·μm（n=6），B 组 n=5。确认的是当前记录，不代表因果或统计显著性成立。':'确认生效日期，避免把本次决策追溯为月初标准。'}</p><blockquote>{m.id==='data'?state.sourceText:meetings[2].speeches[0]}</blockquote><button className="source-link" onClick={()=>source(m.id)}>查看来源或修正 <ArrowUpRight size={13}/></button>{actionButtons(m)}</div>}
 function management(){return <>{state.memories.filter(m=>m.scope==='team'||m.owner===actor).map(m=><details className="memory-row" key={m.id}><summary><span><strong>{m.title}</strong><small>{m.project} · {m.scope==='private'?'仅作者':m.owner+' · 团队'}</small></span><span className="status-pill">{names[m.status]}</span></summary><p>{m.status==='forgotten'?'正文已从项目记忆移除。原会议保留，不自动恢复。':m.text}</p><button className="source-link" onClick={()=>source(m.id)}>{m.source} ↗</button>{actionButtons(m)}{m.id==='private'&&m.owner===actor&&m.status==='confirmed'&&<Button variant="outline" onClick={()=>run(s=>act(s,'private',m.scope==='private'?'share':'unshare',actor),m.scope==='private'?'已共享给 M09 六人，仍保留 Wang 的个人假设归属。':'已撤回共享，其他角色不再调用。')}>{m.scope==='private'?'共享给 M09 六人':'撤回共享'}</Button>}</details>)}<p className="fine-print">忘记项目记忆不删除原始会议。个人笔记需由 Wang 明确共享，始终保留假设性质。</p><details className="audit-list"><summary>操作历史</summary>{state.audit.length?state.audit.map((a,i)=><p key={i}>{a}</p>):<p>尚无操作。</p>}</details></>}
 const sourceRecord=state.memories.find(m=>m.id===selected)!;
 const canSeeSource=sourceRecord.scope==='team'||sourceRecord.owner===actor;
 const editable=sourceMeeting===2&&sourceSpeaker===3;
 return localize(<div className="simple-app"><header className="simple-header demo-header"><a href="/" className="demo-brand" aria-label="Zhixu home"><span>z.</span></a><div className="header-actions demo-header-actions"><a href="/docs" className="demo-guide" data-no-localize>Guide</a><LanguageSwitch language={language} onChange={switchLanguage}/><NativeSelect className="demo-user-select" aria-label="演示角色" value={actor} onChange={e=>switchActor(e.target.value)}>{people.map(p=><NativeSelectOption key={p.name} value={p.name}>{p.name}</NativeSelectOption>)}</NativeSelect></div></header><div className="prototype-note">虚构研究场景 · 本机保存，不跨设备同步 · 角色、AI 与录音均为模拟</div>
 <Tabs value={view} onValueChange={v=>setView(String(v))} className="app-tabs"><div className="simple-nav"><TabsList variant="line"><TabsTrigger value="assistant"><MessageSquare size={16}/>研究助手</TabsTrigger><TabsTrigger value="meetings"><BookOpen size={16}/>会议记录</TabsTrigger></TabsList><div><button onClick={()=>setPanel('memory')} disabled={!ready}><BookOpen size={15}/>项目记忆</button><button onClick={()=>setPanel('history')} disabled={!ready}><History size={15}/>历史会话</button></div></div>
 <main className="simple-main"><fieldset disabled={!ready} className="ready-fieldset"><TabsContent value="assistant"><div className="assistant-heading"><div><span className="eyebrow">M09 / SEPTEMBER RESEARCH</span><h1>今天的研究，从这里继续。</h1><p>三次会议已经在这里。直接提问，相关记忆会随回答出现。</p></div><Button variant="outline" onClick={newChat}><Plus size={16}/>新会话</Button></div>
 {pending.length>0&&<div className="pending-banner"><div><span className="attention-dot"/><strong>{pending.length} 项信息待负责人确认</strong><span>未确认内容不会写入当前结论。</span></div><Button variant="outline" onClick={()=>setReviewOpen(!reviewOpen)}>{reviewOpen?'收起':'就地核查'}</Button></div>}{reviewOpen&&<div className="inline-reviews">{pending.length?pending.map(reviewCard):<div className="confirmed-note"><Check size={17}/>待确认项已处理，可以继续提问。<button onClick={()=>setReviewOpen(false)}>收起</button></div>}</div>}
 <div className="assistant-surface"><div className="composer"><label htmlFor="request">你现在需要完成什么？</label><Textarea id="request" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="例如：帮我准备明天给 Park 教授的汇报" onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();ask()}}}/><div className="composer-bottom"><div className="quick-prompts"><button onClick={()=>ask('帮我准备明天给 Park 教授的研究汇报。')}><MessageSquare size={14}/>准备汇报</button><button onClick={()=>ask('生成本月研究进展月报。')}><FileText size={14}/>生成月报</button><button onClick={()=>ask('下次研究会议应该优先讨论什么？')}>下次会议</button></div><Button disabled={!question.trim()} onClick={()=>ask()} aria-label="发送问题"><ArrowUp size={17}/>发送</Button></div></div>
 {answer?<section className="answer-area" aria-live="polite"><div className="answer-heading"><div><span className="answer-logo">知</span><h2>{current?.question}</h2></div>{answer.revision===state.revision&&<Button variant="outline" onClick={()=>download(answer)}>下载</Button>}</div>{answer.revision!==state.revision?<div className="stale-note">项目记忆已变化，旧回答暂停展示。<Button variant="outline" onClick={()=>ask(current!.question)}>更新这份回答</Button></div>:<><div className="answer-copy">{answer.text.split('\n\n').map(p=><p key={p}>{p}</p>)}</div><div className="source-chips">{answer.used.map(m=><button key={m.id} onClick={()=>source(m.id)}>{m.title}<ArrowUpRight size={12}/></button>)}</div><details className="call-details"><summary>调用详情 · 使用 {answer.used.length} 条，排除 {answer.skipped.length} 条</summary>{answer.used.map(m=><div className="call-detail" key={m.id}><div><strong>{m.title}</strong><p>{m.reason}</p></div><button onClick={()=>toggle(m.id)}>本次不用</button></div>)}{answer.skipped.map(m=><div className="call-detail" key={m.id}><div><strong>{m.title}</strong><p>{m.reason}</p></div>{ignore.includes(m.id)&&<button onClick={()=>toggle(m.id)}>恢复调用</button>}</div>)}<p className="fine-print">本次不用会立即更新回答，不删除记忆。旧版 610 不作为当前数值调用。</p></details></>}</section>:<div className="assistant-empty"><span>从会议到工作，不必重复交代背景。</span><div>{meetings.map((m,i)=><button key={m.title} onClick={()=>{setMeeting(i);setView('meetings')}}><small>{m.date}</small>{m.title}<ChevronRight size={14}/></button>)}</div></div>}</div>
 </TabsContent>
 <TabsContent value="meetings"><div className="assistant-heading"><div><span className="eyebrow">MEETING RECORDS</span><h1>会议总结与核查，放在一起。</h1><p>需要看原话时再展开，处理完可以直接生成汇报。</p></div><Button variant="outline" onClick={()=>setPanel('record')}><Mic size={16}/>模拟记录会议</Button></div><div className="meeting-switch">{meetings.map((m,i)=><Button key={m.title} variant={meeting===i?'default':'outline'} onClick={()=>setMeeting(i)}>{m.date} · {m.title}</Button>)}</div><section className="meeting-surface"><div className="meeting-head"><h2>{meetings[meeting].title}</h2><span>{meetings[meeting].mode} · 六人 · {meetings[meeting].duration}</span></div><p className="meeting-purpose">{meetings[meeting].purpose}</p><div className="meeting-summary">{meeting===2?<><p>{state.sourceDirty?'数据来源已修改，等待可靠提取。':data.status==='forgotten'?'项目数据记忆已忘记，原发言保留。':`B 组当前候选 ${data.value??'待提取'} Ω·μm · ${names[data.status]}。后续判断只使用确认后的版本。`}</p><p>阶段良率门槛为两组均至少 75%，自 9 月 23 日生效；状态：{names[state.memories.find(m=>m.id==='decision')!.status]}。</p><p>修订月报并确认清洗对照安排。机制解释仍是假设。</p></>:meetings[meeting].summary.map(s=><p key={s}>{s}</p>)}{meeting===1&&<p className="historical-note">610 是当时的初步发言，后续已提出修订，不用于当前结论。</p>}</div>{meeting===2&&pending.length>0&&<details className="meeting-review" open><summary>本次会议待确认 · {pending.length} 项</summary>{pending.map(reviewCard)}</details>}
 <details className="transcript-list"><summary>展开原始发言 · 6 位成员</summary>{meetings[meeting].speeches.map((s,i)=><div className="transcript-row" key={i}><span className="person-initial">{people[i].name[0]}</span><div><div className="transcript-meta"><strong>{people[i].name}</strong><span>{people[i].role}</span><time>{timestamps[i]}</time></div><p>{meeting===2&&i===3?state.sourceText:s}</p><button className="source-link" onClick={()=>source(meeting===2&&i===3?'data':i===0?'goal':i===2?'screening':i===4?'hypothesis':'tasks',meeting,i)}>查看详情{meeting===2&&i===3?' / 修正转录':''} ↗</button></div></div>)}</details><div className="meeting-footer"><Button onClick={()=>ask('根据三次会议生成最新研究进展月报。')}>用这些会议生成月报 <ArrowUpRight size={16}/></Button><p>自动筛选有效记忆，未确认内容不写为结论。</p></div></section><details className="team-details"><summary>查看六人团队与分工</summary><div>{people.map(p=><p key={p.name}><strong>{p.name} · {p.role}</strong><span>{p.job}</span></p>)}</div></details></TabsContent></fieldset></main></Tabs>
 <Sheet open={panel!==null} onOpenChange={open=>{if(!open){setPanel(null);setEditing(false)}}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>{panel==='memory'?'项目记忆':panel==='history'?'历史会话':panel==='record'?'模拟记录会议':'来源与操作'}</SheetTitle><SheetDescription>{panel==='source'?'核查与修改都在这里完成，关闭后返回刚才的工作。':panel==='history'?`${actor} 的本机会话，不包含其他角色的对话。`:panel==='memory'?'按需管理，无需离开当前任务。':'只演示设置，不访问摄像头或麦克风。'}</SheetDescription></SheetHeader><div className="sheet-body"><fieldset disabled={!ready} className="ready-fieldset">{panel==='memory'&&management()}{panel==='history'&&<>{state.sessions.filter(s=>s.actor===actor).length?state.sessions.filter(s=>s.actor===actor).slice().reverse().map(s=><button className="history-row" key={s.id} onClick={()=>{setSessionId(s.id);setIgnore(s.answer?.skipped.filter(m=>m.reason==='你选择本次不用').map(m=>m.id)??[]);setQuestion('');setView('assistant');setPanel(null)}}><strong>{s.question||'空白会话'}</strong><small>{s.answer?.revision===state.revision?'已保存':'记忆已更新，打开后可刷新回答'}</small></button>):<p className="fine-print">还没有会话，直接提问即可。</p>}<Button variant="outline" onClick={()=>{newChat();setPanel(null)}}><Plus size={15}/>新会话</Button></>}
 {panel==='source'&&(canSeeSource?<><span className="status-pill">{sourceMeeting>=0?`${meetings[sourceMeeting].date} · ${people[sourceSpeaker].name} · ${timestamps[sourceSpeaker]}`:sourceRecord.source}</span><h3 className="source-title">{sourceMeeting>=0?`${people[sourceSpeaker].name} 的发言`:sourceRecord.title}</h3>{editing?<><label htmlFor="correction">修正原文</label><Textarea id="correction" className="correction-input" value={editText} onChange={e=>setEditText(e.target.value)}/><p className="fine-print">例如将“复核后应为 690 Ω·μm”改为 720，保留 A 组 820 与样本数。无法识别时会暂停数据调用。</p><div className="compact-actions"><Button disabled={!editText.trim()} onClick={()=>{try{const result=saveAndExtract(state,editText,actor);commit(result.state,result.message);setEditing(false)}catch(e){setNotice((e as Error).message)}}}>保存并自动提取</Button><Button variant="outline" onClick={()=>setEditing(false)}>取消</Button></div></>:<><blockquote className="source-quote">{sourceMeeting<0?(sourceRecord.status==='forgotten'?'记忆正文已移除。':sourceRecord.text):editable?state.sourceText:meetings[sourceMeeting].speeches[sourceSpeaker]}</blockquote>{editable&&<><p className="fine-print">当前编辑者：{state.sourceAuthor}</p><Button variant="outline" onClick={()=>{setEditText(t(state.sourceText));setEditing(true)}}>修正这段转录</Button></>}</>}{editable&&<div className="source-review"><h3>{data.value?`当前提取：${data.value} Ω·μm`:'等待可靠提取'}</h3><p>A 组 820（n=6），B 组 n=5。状态：{names[data.status]}。</p>{actionButtons(data)}<p className="fine-print">负责人核对原文和数值后一次确认；不自动代替他人确认。</p></div>}{!editable&&sourceRecord.meeting===sourceMeeting&&sourceRecord.speaker===sourceSpeaker&&actionButtons(sourceRecord)}{sourceMeeting<0&&sourceRecord.id==='private'&&actor==='Wang'&&sourceRecord.status==='confirmed'&&<Button variant="outline" onClick={()=>run(s=>act(s,'private',sourceRecord.scope==='private'?'share':'unshare',actor),'共享范围已更新。')}>{sourceRecord.scope==='private'?'共享给 M09 六人（个人假设）':'撤回共享'}</Button>}{editable&&state.sourceHistory.length>0&&<details className="audit-list"><summary>查看修改历史</summary>{state.sourceHistory.map((h,i)=><div key={i}><small>{h.author}</small><p>{h.text}</p></div>)}</details>}</>:<p>这条个人记录当前不可见。</p>)}
 {panel==='record'&&<><label className="field-label">会议形式<NativeSelect disabled={recording} value={mode} onChange={e=>setMode(e.target.value)}>{['线下','线上','混合'].map(v=><NativeSelectOption key={v} value={v}>{v}</NativeSelectOption>)}</NativeSelect></label><label className="field-label">采集内容<NativeSelect disabled={recording} value={video} onChange={e=>setVideo(e.target.value)}><NativeSelectOption value="仅音频">仅音频</NativeSelectOption><NativeSelectOption value="音频与视频">音频与视频</NativeSelectOption></NativeSelect></label><p className="fine-print">{mode==='线下'?'1 台主设备，6 人；其他设备不开收音。':mode==='线上'?'4 台个人终端 + 1 台双人终端。':'会议室 4 人 + 2 台远程个人终端。'}</p><label className="checkbox-line"><Checkbox checked={consent} disabled={recording} onCheckedChange={v=>setConsent(Boolean(v))}/>模拟全员已知情确认录制</label><Button disabled={!consent} onClick={()=>{setRecording(!recording);setNotice(recording?'模拟记录结束，可查看三次预置会议。':'开始模拟记录，实际设备未开启。')}}>{recording?'结束模拟记录':'开始模拟记录'}</Button><label className="field-label">多人设备声段归属<NativeSelect value={speaker} onChange={e=>setSpeaker(e.target.value)}><NativeSelectOption value="待确认">待确认</NativeSelectOption>{people.map(p=><NativeSelectOption key={p.name}>{p.name}</NativeSelectOption>)}</NativeSelect></label><p className="fine-print">声段 2 → {speaker}。该设置不修改预置转录。</p></>}</fieldset></div></SheetContent></Sheet>
 {notice&&<div className="simple-toast" role="status"><Check size={16}/><span>{notice}</span><button aria-label="关闭提示" onClick={()=>setNotice('')}>×</button></div>}<footer className="simple-footer">知序 · IBS 虚构原型<span>规则演示 · 本机保存 · 无真实身份授权</span></footer></div>);
}




