'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Download,BookOpen,ExternalLink} from 'lucide-react';
import {Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarGroup,SidebarGroupLabel,SidebarGroupContent,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarProvider,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {chapters as chaptersZh} from '@/lib/manual';
import {chaptersEn} from '@/lib/manual.en';
import {LanguageSwitch,useLanguage} from '@/components/language';
import './manual.css';
function Manual(){
 const {language,switchLanguage,localize}=useLanguage();
 const chapters=language==='en'?chaptersEn:chaptersZh;
 const [active,setActive]=useState('start');const {setOpenMobile}=useSidebar();
 useEffect(()=>{const sync=()=>{const id=location.hash.slice(1);setActive(chapters.some(c=>c.id===id)?id:'start');};sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[chapters]);
 const index=chapters.findIndex(c=>c.id===active),chapter=chapters[index]||chapters[0];
 function choose(){setOpenMobile(false);window.scrollTo({top:0,behavior:'instant'});}
 return localize(<><Sidebar className="manual-sidebar"><SidebarHeader><a href="/" className="manual-brand"><span>知</span><strong>知序</strong><small>产品说明书</small></a></SidebarHeader><SidebarContent>{Array.from(new Set(chapters.map(c=>c.group))).map(group=><SidebarGroup key={group}><SidebarGroupLabel>{group}</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>{chapters.filter(c=>c.group===group).map(c=><SidebarMenuItem key={c.id}><SidebarMenuButton isActive={c.id===active} render={<a href={'#'+c.id} onClick={choose}/>}>{c.title}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup>)}</SidebarContent><SidebarFooter><a className="manual-back" href="/"><ArrowLeft size={16}/>返回研究助手</a><small>IBS 虚构场景 · 评审初稿</small></SidebarFooter></Sidebar><div className="manual-main"><header className="manual-topbar"><div><SidebarTrigger/><span>说明书 / {chapter.group}</span></div><LanguageSwitch language={language} onChange={switchLanguage}/><a href="/" className="manual-demo">打开 Demo <ExternalLink size={14}/></a></header><div className="manual-body"><article key={chapter.id}><div className="manual-eyebrow"><BookOpen size={15}/> ZHIXU GUIDE <span>{String(index+1).padStart(2,'0')} / {chapters.length}</span></div><h1>{chapter.title}</h1><p className="manual-intro">{chapter.intro}</p>{(active==='start'||active==='evaluation'||active==='status')&&<div className="manual-downloads"><a href="/deliverables/positioning.pptx" download="知序-产品定位.pptx"><Download size={16}/>产品定位 PPT</a><a href="/deliverables/evaluation.xlsx" download="知序-评测工作簿.xlsx"><Download size={16}/>评测工作簿</a></div>}{chapter.sections.map((s,i)=><section id={'section-'+i} key={s.title}><h2>{s.title}</h2>{s.text&&<p>{s.text}</p>}{s.steps&&<ol>{s.steps.map(t=><li key={t}>{t}</li>)}</ol>}{s.rows&&<div className="manual-table-wrap"><table><thead><tr>{s.columns?.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{s.rows.map((row,r)=><tr key={r}>{row.map((cell,n)=><td key={n}>{cell}</td>)}</tr>)}</tbody></table></div>}{s.note&&<aside className="manual-note">{s.note}</aside>}</section>)}<nav className="manual-pagination" aria-label="章节翻页">{index>0?<a href={'#'+chapters[index-1].id} onClick={choose}><ArrowLeft size={16}/><span><small>上一节</small>{chapters[index-1].title}</span></a>:<span/>}{index<chapters.length-1&&<a href={'#'+chapters[index+1].id} onClick={choose}><span><small>下一节</small>{chapters[index+1].title}</span><ArrowRight size={16}/></a>}</nav><footer className="manual-end">知序 · 长期研究记忆助理 / 2026.09</footer></article><aside className="manual-toc"><span>本页内容</span>{chapter.sections.map((s,i)=><button key={s.title} onClick={()=>document.getElementById('section-'+i)?.scrollIntoView({behavior:'smooth',block:'start'})}>{s.title}</button>)}<a href="/deliverables/evaluation.xlsx" download="知序-评测工作簿.xlsx">下载评测表 <Download size={13}/></a></aside></div></div></>);
}
export default function Docs(){return <SidebarProvider className="manual-shell"><Manual/></SidebarProvider>}
