'use client';
import {useState,useEffect} from 'react';
import {flushSync} from 'react-dom';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Button} from '@/components/ui/button';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Textarea} from '@/components/ui/textarea';
import {people,meetings,timestamps} from '@/lib/scenario';
import {initialState,restore,act,editSource,extract,checkExtraction,recall,type State,type MemoryId,type Answer} from '@/lib/memory';
import {ArrowRight,ArrowUpRight,Check,FlaskConical,Mic} from 'lucide-react';

type View='home'|'meetings'|'review'|'memory'|'chat'|'progress';
const KEY='zhixu-ibs-memory-v3';
export default function Home(){
 const [state,setState]=useState<State>(initialState),[ready,setReady]=useState(false),[storage,setStorage]=useState('正在读取本机记忆…');
 const [view,setView]=useState<View>('home'),[actor,setActor]=useState('Han'),[meeting,setMeeting]=useState(0),[tab,setTab]=useState('summary'),[focus,setFocus]=useState(-1);
 const [notice,setNotice]=useState(''),[editing,setEditing]=useState(false),[text,setText]=useState(''),[sessionId,setSessionId]=useState(''),[question,setQuestion]=useState('帮我准备明天给 Park 教授汇报的内容。'),[ignore,setIgnore]=useState<MemoryId[]>([]),[report,setReport]=useState<Answer|null>(null),[reportActor,setReportActor]=useState('');
 const [mode,setMode]=useState('线下'),[recording,setRecording]=useState(false),[consent,setConsent]=useState(false),[video,setVideo]=useState('仅音频'),[speaker,setSpeaker]=useState('待确认');
 useEffect(()=>{const listener=(event:StorageEvent)=>{if(event.key!==KEY||!event.newValue)return;try{setState(restore(event.newValue));setNotice('已同步同一浏览器其他标签页保存的记忆。')}catch{setNotice('其他标签页的存档无法读取，当前状态未更改。')}};window.addEventListener('storage',listener);return()=>window.removeEventListener('storage',listener)},[]);
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>unknown}}).modelContext;if(!ctx)return;const c=new AbortController();try{Promise.resolve(ctx.registerTool({name:'navigate_research_workspace',description:'打开研究工作台页面，不更改记忆或确认记录。',inputSchema:{type:'object',properties:{page:{type:'string',enum:['home','meetings','review','memory','chat','progress']}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const d=input as {page?:unknown};if(!d||Object.keys(d).length!==1||!['home','meetings','review','memory','chat','progress'].includes(String(d.page)))throw new Error('无效页面');flushSync(()=>setView(d.page as View));return {page:d.page}}},{signal:c.signal})).catch(()=>{});}catch{}return()=>c.abort()},[]);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setState(restore(raw));setStorage('本机记忆已载入')}catch{setStorage('存档无法读取；本次从预置场景开始');setNotice('存档格式不兼容或浏览器存储不可用。请勿将此状态视为云端同步。')}setReady(true)},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(KEY,JSON.stringify(state));setStorage('已保存到本机 · 刷新后保留')}catch{setStorage('保存失败 · 本次变更仅在当前页面');setNotice('浏览器未能保存记忆。关闭页面后，本次变更可能丢失。')}},[state,ready]);
 useEffect(()=>{if(view==='meetings'&&tab==='transcript'&&focus>=0){const id=requestAnimationFrame(()=>document.getElementById(`speech-${focus}`)?.scrollIntoView({behavior:'smooth',block:'center'}));return()=>cancelAnimationFrame(id)}},[view,tab,focus,meeting]);
 function run(fn:(s:State)=>State,message:string){try{setState(fn(state));setNotice(message)}catch(e){setNotice((e as Error).message)}}
 function source(m:number,p:number){if(m<0){setView('memory');return}setMeeting(m);setFocus(p);setTab('transcript');setView('meetings')}
 function newSession(){const id=crypto.randomUUID();setState(s=>({...s,sessions:[...s.sessions,{id,actor,question:'',answer:null}]}));setSessionId(id);setQuestion('帮我准备明天给 Park 教授汇报的内容。');setIgnore([]);setView('chat');setNotice('已开始一个空白会话。项目记忆保留，不附带旧会话内容。')}
 function ask(){if(!question.trim())return;const answer=recall(state,actor,question,ignore);let id=sessionId;const existing=state.sessions.find(s=>s.id===id&&s.actor===actor);if(!existing)id=crypto.randomUUID();setState(s=>({...s,sessions:existing?s.sessions.map(c=>c.id===id?{...c,question:question.trim(),answer}:c):[...s.sessions,{id,actor,question:question.trim(),answer}]}));setSessionId(id)}
 function toggle(id:MemoryId){setIgnore(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]);setNotice('本次调用选择已改变，请重新生成回答。')}
 const data=state.memories.find(m=>m.id==='data')!;const decision=state.memories.find(m=>m.id==='decision')!;
 const currentSession=state.sessions.find(s=>s.id===sessionId&&s.actor===actor);const pending=state.memories.filter(m=>m.project==='M09'&&m.status==='pending').length;
 const visible=state.memories.filter(m=>m.scope==='team'||m.owner===actor);
 const statusName={pending:'待核查',confirmed:'当前有效',rejected:'不保存',forgotten:'已忘记'};
 function controls(id:MemoryId){const m=state.memories.find(x=>x.id===id)!;return <div className="actions">{m.status==='pending'&&<><Button disabled={m.owner!==actor||(id==='data'&&(!state.extracted||state.sourceDirty))} onClick={()=>run(s=>act(s,id,'confirm',actor),'已确认，后续会话将使用当前版本。')}>{m.owner===actor?'确认保存':`由 ${m.owner} 确认`}</Button><Button variant="outline" onClick={()=>run(s=>act(s,id,'reject',actor),'候选不再保存或用于后续回答。')}>不保存</Button></>}{m.status==='confirmed'&&<Button variant="outline" disabled={m.owner!==actor} onClick={()=>run(s=>act(s,id,'forget',actor),'已忘记该项目记忆。后续回答不再调用；原会议记录仍保留。')}>{m.owner===actor?'忘记这条记忆':`由 ${m.owner} 撤回记忆`}</Button>}{m.status==='rejected'&&<Button variant="outline" disabled={actor!==m.owner} onClick={()=>run(s=>act(s,id,'reconsider',actor),'已重新进入候选核查。')}>重新核查</Button>}</div>}
 function explanation(answer:Answer){return <div className="call-log"><h3>为什么调用这些记忆？</h3>{answer.used.length===0&&<p className="muted">本次没有使用项目记忆。</p>}{answer.used.map(m=><div className="call-row" key={m.id}><div><strong>{m.title}</strong><p>{m.reason}</p><button className="text-link" onClick={()=>source(m.meeting,m.speaker)}>{m.source} ↗</button></div><Button variant="outline" onClick={()=>toggle(m.id)}>{ignore.includes(m.id)?'恢复本次调用':'本次不用'}</Button></div>)}<details open><summary>未调用的记录 · {answer.skipped.length}</summary>{answer.skipped.map(m=><p key={m.id}><strong>{m.title}</strong>：{m.reason}{ignore.includes(m.id)&&<button className="text-link" onClick={()=>toggle(m.id)}>　恢复本次调用</button>}</p>)}</details><p className="muted">旧版 610 不再作为当前数据调用。私有笔记不会向其他演示角色展示内容或标题。</p></div>}
 return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">知</span>知序<span className="brand-sub">研究团队工作台</span></div><div className="role-picker"><span>演示视角</span><NativeSelect aria-label="切换演示角色" value={actor} onChange={e=>{setActor(e.target.value);setSessionId('');setIgnore([]);setReport(null)}}>{people.map(p=><NativeSelectOption key={p.name} value={p.name}>{p.name} · {p.role.split(' · ')[0]}</NativeSelectOption>)}</NativeSelect></div></header>
 <div className="demo-strip">IBS 虚构场景 · 固定规则演示，无真实模型或音视频采集；角色模拟不是真实权限。<strong>{storage}</strong> · 不跨设备同步。</div>
 <Tabs value={view} onValueChange={v=>setView(v as View)} className="root-tabs"><div className="navline"><span className="workspace-name"><FlaskConical size={17}/>二维半导体 · M09</span><TabsList variant="line" className="main-nav"><TabsTrigger value="home">项目首页</TabsTrigger><TabsTrigger value="meetings">会议记录</TabsTrigger><TabsTrigger value="review">核查 <span className="count">{pending}</span></TabsTrigger><TabsTrigger value="memory">项目记忆</TabsTrigger><TabsTrigger value="chat">新会话</TabsTrigger><TabsTrigger value="progress">月度进展</TabsTrigger></TabsList></div><div className="page-wrap"><fieldset disabled={!ready} className="ready-fieldset">
 <TabsContent value="home"><div className="page-heading"><div><div className="eyebrow">IBS / LONG-TERM RESEARCH MEMORY</div><h1>离开会议，研究仍能接着继续。</h1><p className="subtitle">六位成员，三次会议。一份可追溯、可纠正的项目记忆。</p></div><Button onClick={newSession}>开始一个新会话 <ArrowRight size={16}/></Button></div>
 <div className="onboarding"><div className="circle-number">1</div><div><strong>先看讨论，再核查，最后开始新会话。</strong><p>会议信息保存为项目记忆；关闭再打开，也能继续。新会话不会附带旧对话。</p></div><Button variant="outline" onClick={()=>{setMeeting(0);setTab('summary');setView('meetings')}}>查看第一次会议</Button></div>
 <div className="home-grid"><section><div className="section-head"><h2>本月三次会议</h2><span>9 月 · 模拟研究周期</span></div><div className="meeting-list">{meetings.map((m,i)=><button key={m.title} className="meeting-tile" onClick={()=>{setMeeting(i);setTab('summary');setFocus(-1);setView('meetings')}}><div className="calendar"><small>SEP</small><strong>{m.date.slice(3)}</strong></div><div className="meeting-info"><h3>{m.title}</h3><p>{m.purpose}</p><small>{m.mode} · 6 人 · {m.duration}</small></div><ArrowUpRight size={18}/></button>)}</div><div className="section-head team-head"><h2>项目团队</h2><span>各自负责，保留归属</span></div><div className="team-grid">{people.map((p,i)=><div className="person" key={p.name}><span className={`avatar tone-${i}`}>{p.name[0]}</span><div><strong>{p.name}</strong><small>{p.role}</small><small>{p.job}</small></div></div>)}</div></section><aside><div className="dark-card"><div className="eyebrow">下一次工作</div><h2>“帮我准备明天<br/>给 Park 的汇报。”</h2><p>无需复制三次会议。知序会筛选当前有效的目标、数据和行动项，并解释哪些记录没有使用。</p><Button variant="outline" onClick={newSession}>体验跨会话调用</Button></div><div className="attention"><h3>{data.status==='confirmed'?`当前数据：${data.value} Ω·μm`:'重要数值还不能直接引用'}</h3><p>第三次会议修订了旧数据。未确认、被拒绝和已忘记的信息，都不会作为当前事实进入报告。</p><Button variant="outline" onClick={()=>setView('review')}>前往核查工作台</Button></div></aside></div></TabsContent>
 <TabsContent value="meetings"><div className="page-heading"><div><div className="eyebrow">MEETING RECORDS</div><h1>原话保留，变化有据。</h1><p className="subtitle">记录是来源；项目记忆是经过核查、带版本的解释。</p></div></div><div className="meeting-picker">{meetings.map((m,i)=><Button key={m.title} variant={meeting===i?'default':'outline'} onClick={()=>{setMeeting(i);setTab('summary');setFocus(-1);setEditing(false)}}>{m.date} · {m.title}</Button>)}</div>
 <div className="detail-grid"><section className="surface"><div className="meeting-title"><div><span className="pill">{meetings[meeting].mode} · 六人</span><h2>{meetings[meeting].title}会议</h2><p>{meetings[meeting].purpose}</p></div></div><Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList variant="line"><TabsTrigger value="summary">会议总结</TabsTrigger><TabsTrigger value="transcript">六人发言与来源</TabsTrigger></TabsList><TabsContent value="summary"><div className="summary-body">{meeting!==2?meetings[meeting].summary.map((s,i)=><div className="summary-item" key={s}><span>0{i+1}</span><p>{s}</p></div>):<><div className="summary-item"><p>{state.sourceDirty?'关键转录已修改，数值总结暂停，等待重新提取。':data.status==='forgotten'?'相关项目记忆已忘记，请查看原文；不会自动重新保存。':`当前提取：B 组 ${data.value??'待提取'} Ω·μm，A 组 820 Ω·μm。状态：${statusName[data.status]}。`}</p></div><div className="summary-item"><p>Park 提出两组初筛通过率至少 75%，自 9 月 23 日适用。状态：{statusName[decision.status]}。</p></div><div className="summary-item"><p>原会议中的 15.9% 是当时发言；后续计算只使用当前确认的数据，不沿用旧结论。</p></div></>}{meeting===1&&<div className="inline-warning">这是历史会议：610 是当日初步陈述，后来被提出纠正，不作为当前数据引用。</div>}<Button onClick={()=>{setTab('transcript');setFocus(-1)}}>核对每个人的发言</Button></div></TabsContent><TabsContent value="transcript"><p className="transcript-note muted">模拟时间戳，无真实媒体文件。可编辑第三次会议 Choi 的发言，体验完整纠错。</p>{meetings[meeting].speeches.map((s,i)=><div id={`speech-${i}`} key={i} className={`speech ${focus===i?'highlight':''}`}><span className={`avatar tone-${i}`}>{people[i].name[0]}</span><div><div className="speech-meta"><strong>{people[i].name}</strong><span>{people[i].role}</span><time>{timestamps[i]}</time></div><p>{meeting===2&&i===3?state.sourceText:s}</p>{meeting===2&&i===3&&<><p className="muted">当前转录版本编辑者：{state.sourceAuthor}</p>{editing?<div className="edit-transcript"><label htmlFor="source-text">修正转录（可把 690 改成 720，保留其他口径）</label><Textarea id="source-text" value={text} onChange={e=>setText(e.target.value)}/><div className="actions"><Button disabled={!text.trim()} onClick={()=>{run(s=>editSource(s,text,actor),'已修正转录；旧摘要与数据暂停调用，请重新提取。');setEditing(false)}}>保存修改</Button><Button variant="outline" onClick={()=>setEditing(false)}>取消</Button></div></div>:<div className="actions"><Button variant="outline" onClick={()=>{setText(state.sourceText);setEditing(true)}}>修正转录文字</Button><Button onClick={()=>setView('review')}>重新提取与核查</Button></div>}{state.sourceHistory.length>0&&<details><summary>修改历史 · {state.sourceHistory.length}</summary>{state.sourceHistory.map((h,j)=><div key={j}><small>{h.author}</small><p>{h.text}</p></div>)}</details>}</>}</div></div>)}</TabsContent></Tabs><div className="surface-footer"><Button variant="outline" onClick={()=>{if(meeting<2){setMeeting(meeting+1);setTab('summary')}else setView('review')}}>{meeting<2?'继续下一次会议':'核查重要信息'} <ArrowRight size={16}/></Button></div></section>
 <aside><div className="side-card"><Mic/><h3>一场会议，一份共享记录</h3><p>线下由主设备记录；线上保留终端音轨；多人同设备需要进一步区分声段和确认姓名。</p><p className="muted">当前为固定脚本，未采集音视频。</p></div><details className="side-card"><summary>模拟会议采集设置</summary><label>会议形式<NativeSelect disabled={recording} value={mode} onChange={e=>setMode(e.target.value)}>{['线下','线上','混合'].map(m=><NativeSelectOption key={m}>{m}</NativeSelectOption>)}</NativeSelect></label><label>采集内容<NativeSelect disabled={recording} value={video} onChange={e=>setVideo(e.target.value)}><NativeSelectOption>仅音频</NativeSelectOption><NativeSelectOption>音频与视频</NativeSelectOption></NativeSelect></label><p>{mode==='线下'?'1 台主设备 / 6 人':mode==='线上'?'4 台个人设备 + 1 台双人设备':'会议室设备 / 4 人 + 2 台远程设备'}</p><Button variant="outline" disabled={recording} onClick={()=>setConsent(!consent)}>{consent?'✓ 已模拟全员知情确认':'模拟全员知情确认'}</Button><p><Button disabled={!consent} onClick={()=>{setRecording(!recording);setNotice(recording?'模拟记录结束，可查看预置会议内容。':'开始模拟；实际设备未开启。')}}>{recording?'结束模拟记录':'开始模拟记录'}</Button></p><label>声段 2 的归属<NativeSelect value={speaker} onChange={e=>setSpeaker(e.target.value)}><NativeSelectOption>待确认</NativeSelectOption>{people.map(p=><NativeSelectOption key={p.name}>{p.name}</NativeSelectOption>)}</NativeSelect></label><p>映射示例：{speaker}。不修改历史会议。</p></details></aside></div></TabsContent>
 <TabsContent value="review"><div className="page-heading"><div><div className="eyebrow">REVIEW & CORRECTION</div><h1>修改之后，重新建立可信依据。</h1><p className="subtitle">整理者核查提取，Choi 确认数据，Park 确认项目决策。</p></div><Button variant="outline" onClick={()=>setView('memory')}>查看全部记忆</Button></div><div className="review-grid"><section><div className="review-card"><span className="pill">1 · 当前转录 → 候选提取</span><h2>先确认 AI 提取的是当前原话</h2><blockquote className="source-quote">{state.sourceText}</blockquote><button className="text-link" onClick={()=>source(2,3)}>查看转录与编辑历史 ↗</button><div className="inline-info">{state.sourceDirty?'来源已修改，必须重新提取。':data.value?`候选：B 组 ${data.value} Ω·μm（n=5），A 组 820 Ω·μm（n=6）。`:'没有可用候选，可从原文重新提取。'}</div><div className="actions"><Button variant="outline" onClick={()=>run(s=>extract(s,actor),'已重新提取。请核查后再由 Choi 确认。')}>从当前转录重新提取</Button><Button disabled={state.sourceDirty||!data.value||state.extracted} onClick={()=>run(s=>checkExtraction(s,actor),'提取已核查，不等于科研数据真实。')}>{state.extracted?'✓ 提取已核查':'确认提取符合原文'}</Button></div><p className="muted">使用保守规则解析示例格式；无法识别的内容会报错，不猜测。已忘记的记忆只有主动重新提取才会进入候选。</p></div><div className="review-card"><span className="pill orange">2 · 数据负责人确认</span><h2>{data.value?`${data.value} Ω·μm`:'等待提取'} · {statusName[data.status]}</h2><p>旧版 610 保留在历史会议中，不再用于当前回答。候选被确认前，不计算当前降幅或判断目标是否达成。</p>{controls('data')}</div><div className="review-card"><span className="pill">3 · 项目决策确认</span><h2>75% 门槛 · {statusName[decision.status]}</h2><p>自 9 月 23 日起，两组初筛通过率均须达到门槛，不能追溯为月初标准。</p><button className="text-link" onClick={()=>source(2,0)}>查看 Park 的原始发言 ↗</button>{controls('decision')}</div><Button onClick={newSession}>核查完成，开始新会话 <ArrowRight size={16}/></Button></section><aside><div className="side-card sticky"><h3>纠错如何影响后续工作？</h3><ol className="explain-list"><li>转录修改：相关数据立即暂停调用。</li><li>重新提取：产生候选，不能直接变成事实。</li><li>负责人确认：新版本参与后续回答。</li><li>历史回答：标记过期，需重新生成。</li></ol><h3>操作记录</h3>{state.audit.length?state.audit.slice(0,8).map((a,i)=><p className="audit" key={i}>{a}</p>):<p>还没有核查操作。</p>}</div></aside></div></TabsContent>
 <TabsContent value="memory"><div className="page-heading"><div><div className="eyebrow">PROJECT MEMORY / LOCAL DEVICE</div><h1>记住什么，由你掌握。</h1><p className="subtitle">记忆与原始会议分开保存。“忘记”退出后续调用，不删除原会议；不会自动重新提取。</p></div><Button onClick={newSession}>去新会话验证</Button></div><div className="memory-grid">{visible.map(m=><div className="review-card" key={m.id}><div className="review-top"><span className="pill">{m.project} · {m.scope==='private'?'仅作者':'团队范围'}</span><span className="status">{statusName[m.status]} · v{m.version}</span></div><h2>{m.title}</h2><p>{m.status==='forgotten'?'正文已从项目记忆移除。原会议独立保留；不会在新回答中自动恢复。':m.text}</p><p className="muted">归属：{m.owner} · {m.source}</p><button className="text-link" onClick={()=>source(m.meeting,m.speaker)}>{m.meeting>=0?'查看来源 ↗':'笔记来源在本卡片'}</button>{m.id!=='other'&&controls(m.id)}{m.id==='private'&&actor==='Wang'&&m.status==='confirmed'&&<div className="actions"><Button onClick={()=>run(s=>act(s,'private',m.scope==='private'?'share':'unshare',actor),m.scope==='private'?'已模拟共享给 M09 六人，仍是 Wang 的假设，不是团队结论。':'已撤回共享，其他角色不再调用。')}>{m.scope==='private'?'共享给 M09 六人（保留个人假设）':'撤回团队共享'}</Button></div>}</div>)}</div><div className="inline-info">切换到 Wang 查看个人笔记。共享后切换到 Han 开新会话，可看到有署名的假设；撤回后，其他角色不能再次调用。实际数据仅在本机，同一浏览器角色切换不是真实权限隔离。</div></TabsContent>
 <TabsContent value="chat"><div className="page-heading"><div><div className="eyebrow">A NEW SESSION / {actor.toUpperCase()}</div><h1>几天后，再次打开知序。</h1><p className="subtitle">新会话没有旧对话。只有经过筛选的项目记忆，继续帮助当前工作。</p></div><Button onClick={newSession}>＋ 新建空白会话</Button></div><div className="chat-grid"><section className="surface report-surface"><label htmlFor="question">今天要做什么？</label><Textarea id="question" value={question} onChange={e=>setQuestion(e.target.value)} className="question-input"/><div className="prompt-options"><button onClick={()=>setQuestion('帮我准备明天给 Park 教授汇报的内容。')}>准备教授汇报</button><button onClick={()=>setQuestion('下一次会议应该优先讨论哪些研究问题？')}>准备下次会议</button><button onClick={()=>setQuestion('帮我挑选一份晚餐菜单。')}>试试无关问题</button></div><div className="actions"><Button disabled={!question.trim()} onClick={ask}>发送，调用相关记忆</Button><Button variant="outline" onClick={()=>setView('memory')}>管理记忆</Button></div><p className="muted">规则演示支持研究进展、汇报和会议准备；其他问题不生成通用回答。</p>{currentSession?.answer&&<div className="report" aria-live="polite"><small>本会话请求：{currentSession.question}</small>{currentSession.answer.revision!==state.revision?<div className="inline-warning">记忆或共享范围已改变，旧回答暂停展示，避免沿用已撤回内容。点击发送重新生成。</div>:<>{currentSession.answer.text.split('\n\n').map(p=><p key={p}>{p}</p>)}{explanation(currentSession.answer)}</>}</div>}</section><aside><div className="side-card"><h3>保留的会话 · {actor}</h3><p>只显示当前角色的会话。切换角色不会继承别人的对话。</p>{state.sessions.filter(s=>s.actor===actor).slice().reverse().map((s,i)=><button className="session-link" key={s.id} onClick={()=>{setSessionId(s.id);setQuestion(s.question||'帮我准备明天给 Park 教授汇报的内容。');setIgnore([])}}>{s.question||'空白会话'}<small>{s.answer?`使用 ${s.answer.used.length} 条记忆`:'尚未发送'} · {s.answer&&s.answer.revision!==state.revision?'需更新':`会话 ${state.sessions.filter(x=>x.actor===actor).length-i}`}</small></button>)}{!state.sessions.some(s=>s.actor===actor)&&<p className="muted">点击发送即可创建第一个会话。</p>}</div><div className="side-card"><h3>本次调用设置</h3><p>点回答依据中的“本次不用”，然后重新发送。不会删除长期记忆。</p>{ignore.map(id=><p key={id}>{state.memories.find(m=>m.id===id)?.title} <button className="text-link" onClick={()=>toggle(id)}>恢复</button></p>)}<p className="muted">其他项目 P08 的数据因材料与口径不同而排除；不会直接混入 M09。</p></div></aside></div></TabsContent>
 <TabsContent value="progress"><div className="page-heading"><div><div className="eyebrow">MONTHLY PROGRESS</div><h1>月报也遵循同一套记忆规则。</h1><p className="subtitle">与新会话共用筛选逻辑，忘记、拒绝和版本变更同样生效。</p></div><Button variant="outline" onClick={()=>setView('review')}>回到核查</Button></div><div className="surface report-surface"><Button onClick={()=>{setReport(recall(state,actor,'生成本月研究进展报告',ignore));setReportActor(actor)}}>生成当前月报</Button>{report&&<div className="report">{report.revision!==state.revision||reportActor!==actor?<div className="inline-warning">记忆或角色已变化，请重新生成。</div>:<>{report.text.split('\n\n').map(p=><p key={p}>{p}</p>)}{explanation(report)}<Button variant="outline" onClick={()=>{const blob=new Blob([`# IBS 虚构研究场景 · 月报\n\n${report.text}\n\n依据：\n${report.used.map(m=>`${m.title}：${m.source}`).join('\n')}`],{type:'text/markdown;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='知序-最新月报.md';a.click();URL.revokeObjectURL(url)}}>下载当前月报</Button></>}</div>}<details className="old-draft"><summary>预置旧月报 · 只供追溯，不参与生成</summary><p>“B 组初步数据为 610 Ω·μm，相对降低 25.6%，超过月初目标。”</p><div className="inline-warning">第三次会议提出修订后，该草稿失效。原文保留，新报告不沿用。</div></details></div></TabsContent>
 </fieldset>{notice&&<div className="feedback" role="status"><Check size={18}/>{notice}<button aria-label="关闭提示" onClick={()=>setNotice('')}>×</button></div>}</div></Tabs><footer><span>知序 · IBS 虚构研究场景</span><span>{ready?storage:'正在载入'} / 模拟团队，不跨设备同步</span></footer></div>
}

