'use client';
import { useState, useEffect } from 'react';
import { flushSync } from 'react-dom';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { Textarea } from '@/components/ui/textarea';
import { people, meetings, timestamps, initialReview, confirmReview, makeReport, type ReviewState } from '@/lib/scenario';
import { ArrowUpRight, ArrowRight, Mic, Check, FileText, GitBranch, CircleAlert, FlaskConical } from 'lucide-react';

type View='home'|'meetings'|'review'|'progress';
export default function Home(){
 const [view,setView]=useState<View>('home');
 const [meeting,setMeeting]=useState(0),[actor,setActor]=useState('Han'),[review,setReview]=useState(initialReview);
 const [focus,setFocus]=useState(-1),[detailTab,setDetailTab]=useState('summary');
 const [notice,setNotice]=useState(''),[draft,setDraft]=useState(''),[draftState,setDraftState]=useState('');
 const [mode,setMode]=useState('线下'),[capture,setCapture]=useState(0),[camera,setCamera]=useState('仅音频'),[consent,setConsent]=useState(false);
 const [speaker,setSpeaker]=useState('待确认'),[edit,setEdit]=useState(false),[editText,setEditText]=useState(''),[overrides,setOverrides]=useState<Record<string,string>>({});
 const [audit,setAudit]=useState<string[]>([]);
 const pending=3-Number(review.extraction)-Number(review.data)-Number(review.decision);
 function navigate(v:View){setView(v);setNotice('')}
 function source(m:number,p:number){setMeeting(m);setFocus(p);setDetailTab('transcript');navigate('meetings')}
 function confirm(kind:keyof ReviewState){try{setReview(confirmReview(review,kind,actor));setNotice(kind==='extraction'?'提取已核查；这不代表数据已复核。':kind==='data'?'690 已作为当前有效版本；610 仅供历史追溯。':'75% 门槛已生效，日期保留为 9 月 23 日。');setAudit(a=>[`${actor} · ${kind==='extraction'?'核查 09.12 数字提取':kind==='data'?'确认 690 Ω·μm 替代 610':'确认 75% 门槛，生效日 09.23'}`,...a])}catch(e){setNotice((e as Error).message)}}
 function exportDraft(){const blob=new Blob([`# IBS 二维材料项目 · 九月进展摘要\n\n虚构研究场景，固定脚本演示。\n\n${draft}`],{type:'text/markdown;charset=utf-8'});const a=document.createElement('a');const url=URL.createObjectURL(blob);a.href=url;a.download='知序-九月进展摘要.md';a.click();URL.revokeObjectURL(url)}
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>unknown}}).modelContext;if(!ctx)return;const c=new AbortController();try{Promise.resolve(ctx.registerTool({name:'navigate_research_workspace',description:'打开研究工作台页面，不修改或确认研究记录。',inputSchema:{type:'object',properties:{page:{type:'string',enum:['home','meetings','review','progress']}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const d=input as {page?:unknown};if(!d||Object.keys(d).length!==1||!['home','meetings','review','progress'].includes(String(d.page)))throw new Error('无效页面');flushSync(()=>setView(d.page as View));return {page:d.page}}},{signal:c.signal})).catch(()=>{});}catch{}return()=>c.abort()},[]);
 const current=meetings[meeting];
 useEffect(()=>{if(view==='meetings'&&detailTab==='transcript'&&focus>=0){const frame=requestAnimationFrame(()=>document.getElementById(`speech-${focus}`)?.scrollIntoView({behavior:'smooth',block:'center'}));return()=>cancelAnimationFrame(frame)}},[view,detailTab,focus,meeting]);
 return <div className="app-shell">
 <header className="topbar"><div className="brand"><span className="brand-mark">知</span>知序<span className="brand-sub">研究团队工作台</span></div><div className="role-picker"><span>演示视角</span><NativeSelect aria-label="切换演示角色" value={actor} onChange={e=>setActor(e.target.value)}>{people.map(p=><NativeSelectOption key={p.name} value={p.name}>{p.name} · {p.role.split(' · ')[0]}</NativeSelectOption>)}</NativeSelect></div></header>
 <div className="demo-strip">IBS 背景虚构演示 · 人物、会议和科研数据均为模拟；角色切换不是真实授权。无音视频采集，刷新重置本次操作。</div>
 <Tabs value={view} onValueChange={v=>navigate(v as View)} className="root-tabs">
 <div className="navline"><span className="workspace-name"><FlaskConical size={17}/>二维半导体 · 接触工程</span><TabsList variant="line" className="main-nav"><TabsTrigger value="home">项目首页</TabsTrigger><TabsTrigger value="meetings">会议记录</TabsTrigger><TabsTrigger value="review">核查工作台 <span className="count">{pending}</span></TabsTrigger><TabsTrigger value="progress">项目进展</TabsTrigger></TabsList></div>
 <div className="page-wrap">
 <TabsContent value="home"><div className="page-heading"><div><div className="eyebrow">IBS / 2D MATERIALS RESEARCH</div><h1>从每次讨论，走向下一步发现。</h1><p className="subtitle">九月研究周期 · M09 材料批次 · 6 位成员</p></div><span className="month">SEP <strong>2026</strong></span></div>
 <div className="onboarding"><div className="circle-number">1</div><div><strong>第一次使用？从 9 月 2 日会议开始。</strong><p>看六人的讨论如何被整理，再核查数据变化，最后生成项目进展。</p></div><Button onClick={()=>{setMeeting(0);setDetailTab('summary');navigate('meetings')}}>查看第一次会议 <ArrowRight size={16}/></Button></div>
 <div className="home-grid"><section><div className="section-head"><h2>本月三次会议</h2><span>同一项目，持续积累</span></div><div className="meeting-list">{meetings.map((m,i)=><button className="meeting-tile" key={m.title} onClick={()=>{setMeeting(i);setDetailTab('summary');setFocus(-1);navigate('meetings')}}><div className="calendar"><small>SEP</small><strong>{m.date.slice(3)}</strong></div><div className="meeting-info"><div className="row"><h3>{m.title}</h3><span className={`pill ${i===2?'orange':''}`}>{i===0?'目标与分工':i===1?'初步数据':'数据变更'}</span></div><p>{m.purpose}</p><small>{m.mode}会议 · 6 人 · {m.duration}</small></div><ArrowUpRight size={19}/></button>)}</div>
 <div className="section-head team-head"><h2>项目团队</h2><span>每人都有知序入口，共用会议记录</span></div><div className="team-grid">{people.map((p,i)=><div className="person" key={p.name}><span className={`avatar tone-${i}`}>{p.name.slice(0,1)}</span><div><strong>{p.name}</strong><small>{p.role}</small><small>{p.job}</small></div></div>)}</div></section>
 <aside><div className="dark-card"><span className="eyebrow">本月研究目标</span><h2>降低接触电阻<br/><strong>20%</strong></h2><p>比较 A 对照组与 B 处理组。目标不等于结果，解释必须保留实验口径。</p><button className="text-link light" onClick={()=>source(0,0)}>查看 Park 的原始发言 ↗</button></div><div className="attention"><CircleAlert size={21}/><h3>{review.data?'数据修订已确认':'月报前，有一处关键变化'}</h3><p>{review.data?'B 组当前有效值为 690 Ω·μm。旧月报中的 610 与 25.6% 需要更新。':'Choi 在第三次会议将 B 组中位数从 610 修正为 690 Ω·μm，影响目标是否达成的判断。'}</p><Button variant="outline" onClick={()=>navigate('review')}>{pending?'查看待核查事项':'查看核查记录'} <ArrowRight size={16}/></Button></div></aside></div>
 </TabsContent>
 <TabsContent value="meetings"><div className="page-heading"><div><div className="eyebrow">MEETING NOTES</div><h1>讨论有记录，结论有来处。</h1><p className="subtitle">先看会议总结；有疑问时，回到带说话人与时间戳的发言。</p></div></div>
 <div className="meeting-picker">{meetings.map((m,i)=><Button variant={meeting===i?'default':'outline'} key={m.title} onClick={()=>{setMeeting(i);setFocus(-1);setDetailTab('summary');setEdit(false)}}>{m.date} · {m.title}</Button>)}</div>
 <div className="detail-grid"><section className="surface"><div className="meeting-title"><div><span className="pill">{current.mode} · {current.duration}</span><h2>{current.title}会议</h2><p>{current.purpose}</p></div><div className="participants">{people.map(p=><span title={p.name} key={p.name}>{p.name[0]}</span>)}</div></div>
 <Tabs value={detailTab} onValueChange={v=>setDetailTab(String(v))}><TabsList variant="line"><TabsTrigger value="summary">AI 总结</TabsTrigger><TabsTrigger value="transcript">发言转录 · 6 人</TabsTrigger></TabsList><TabsContent value="summary"><div className="summary-body"><span className="muted">预置 AI 总结示例 · 可回到原文核查</span>{meeting===2&&overrides['2-3']&&<div className="inline-warning">关键转录已修改：以下总结尚未重新提取，需复核。请到发言转录还原预置片段后继续演示。</div>}{current.summary.map((s,i)=><div className="summary-item" key={s}><span>0{i+1}</span><p>{s}</p></div>)}{meeting===1&&<div className="inline-warning">历史会议记录：610 是当日的初步陈述。9 月 23 日提出修订，不能继续直接用于当前结论。</div>}{meeting===2&&<div className="inline-warning">提取正确与数据复核是两步。当前变更：{review.data?'Choi 已确认':'等待 Choi 确认'}；决策：{review.decision?'Park 已确认':'等待 Park 确认'}。</div>}<Button onClick={()=>{setDetailTab('transcript');setFocus(-1)}}>查看每个人的发言 <ArrowRight size={16}/></Button></div></TabsContent>
 <TabsContent value="transcript"><p className="muted transcript-note">模拟转录片段，时间戳用于定位。未附真实音视频，不能播放录音。</p>{current.speeches.map((speech,i)=>{const key=`${meeting}-${i}`;return <div className={`speech ${focus===i?'highlight':''}`} id={`speech-${i}`} key={key}><span className={`avatar tone-${i}`}>{people[i].name[0]}</span><div><div className="speech-meta"><strong>{people[i].name}</strong><span>{people[i].role}</span><time>{timestamps[i]}</time></div><p>{overrides[key]??speech}</p>{overrides[key]&&<details><summary>查看修改前的转录</summary><p>{speech}</p><small>修改者：Han（模拟整理操作）；需重新核查摘要，不自动更新科研数据。</small></details>}{focus===i&&<span className="pill">当前引用来源</span>}{meeting===2&&i===3&&<div className="edit-transcript">{edit?<><label htmlFor="transcript-edit">修正转录文字</label><Textarea id="transcript-edit" value={editText} onChange={e=>setEditText(e.target.value)}/><div className="actions"><Button disabled={!editText.trim()} onClick={()=>{setOverrides(o=>({...o,[key]:editText.trim()}));setEdit(false);setNotice('转录已修改。相关总结已标记需复核，修改不会直接替代项目数值。')}}>保存转录修正</Button><Button variant="outline" onClick={()=>setEdit(false)}>取消</Button></div></>:<Button variant="outline" onClick={()=>{setEditText(overrides[key]??speech);setEdit(true)}}>修正听写文字</Button>}</div>}</div></div>})}{overrides['2-3']&&meeting===2&&<div className="inline-warning">关键来源已编辑，AI 总结和数据确认已暂停。请还原预置片段后继续本演示。<Button variant="outline" onClick={()=>{setOverrides(o=>{const n={...o};delete n['2-3'];return n});setNotice('预置转录已还原。')}}>还原预置片段</Button></div>}</TabsContent></Tabs>
 <div className="surface-footer"><Button variant="outline" onClick={()=>{if(meeting<2){setMeeting(meeting+1);setFocus(-1);setDetailTab('summary')}else navigate('review')}}>{meeting<2?'继续下一次会议':'去核查重要信息'} <ArrowRight size={16}/></Button></div></section>
 <aside><div className="side-card"><Mic size={22}/><h3>一场会议，一份记录</h3><p>{meeting===0?'会议室一台主设备采集，六人的设备查看同一份记录。':meeting===1?'终端音轨分别记录。同一设备可能有多人，姓名仍需核对。':'会议室主设备与远程终端共同接入，需要处理重复收音。'}</p><div className="line-item"><span>记录方式</span><strong>{current.mode}</strong></div><div className="line-item"><span>说话人</span><strong>6 位 · 已预置</strong></div><div className="line-item"><span>音视频</span><strong>演示未采集</strong></div></div><div className="side-card"><GitBranch size={22}/><h3>从会议到项目记忆</h3><p>原始转录保留历史发言；总结提炼信息；核查后的记录用于后续工作。</p><Button onClick={()=>navigate('review')}>打开核查工作台</Button></div><details className="side-card"><summary>如何开始记录会议？</summary><p>以下只模拟设备设置，不访问摄像头或麦克风。</p><label>会议形式<NativeSelect value={mode} disabled={capture===1} onChange={e=>setMode(e.target.value)}>{['线下','线上','混合'].map(v=><NativeSelectOption key={v}>{v}</NativeSelectOption>)}</NativeSelect></label><label>采集选项<NativeSelect value={camera} disabled={capture===1} onChange={e=>setCamera(e.target.value)}>{['仅音频','音频与视频'].map(v=><NativeSelectOption key={v}>{v}</NativeSelectOption>)}</NativeSelect></label><p>{mode==='线下'?'1 台会议室主设备，6 人共用；其他设备不开收音。':mode==='线上'?'4 个个人终端 + 1 个双人终端；共 6 人。':'1 台会议室设备（4 人）+ 2 个远程个人终端。'}</p><Button variant="outline" disabled={capture===1} onClick={()=>setConsent(!consent)}>{consent?'✓ 已模拟完成录制知情确认':'模拟全员知情确认'}</Button><p><Button disabled={!consent} onClick={()=>setCapture(capture===1?2:1)}>{capture===1?'结束模拟记录':capture===2?'重新模拟记录':'开始模拟记录'}</Button></p>{capture>0&&<div className="inline-info">{capture===1?`正在模拟 ${camera}记录；设备未开启。`:'模拟记录结束：可查看上方已预置的会议转录与总结。'}</div>}<label>多人声段归属<NativeSelect value={speaker} onChange={e=>setSpeaker(e.target.value)}><NativeSelectOption>待确认</NativeSelectOption>{people.map(p=><NativeSelectOption key={p.name}>{p.name}</NativeSelectOption>)}</NativeSelect></label><small>示例声段 2 → {speaker}。只演示映射，不修改历史会议的预置归属。</small></details></aside></div>
 </TabsContent>
 <TabsContent value="review"><div className="page-heading"><div><div className="eyebrow">REVIEW / {pending} PENDING</div><h1>把需要判断的地方，交给对的人。</h1><p className="subtitle">你正在以 {actor} 的演示视角操作。切换右上角角色，体验整理者与负责人的边界。</p></div></div><div className="review-grid"><section><div className="review-card"><div className="review-top"><span className="step-dot">1</span><span className="pill">转录与提取核查</span><span className="status">{review.extraction?'已核查':'Han 可核查'}</span></div><h2>610 是会议原话，还是 AI 听错了？</h2><p>9 月 12 日 Choi 确实报告了 610 Ω·μm。这次确认只证明提取忠实于发言，不能把“今晚复核”标记为已复核。</p><div className="evidence"><span>提取结果</span><strong>B 组 · 中位数 610 Ω·μm · n = 5</strong><button className="text-link" onClick={()=>source(1,3)}>来源：Choi / 09.12 / 18:42 ↗</button></div><Button disabled={review.extraction} onClick={()=>confirm('extraction')}>{review.extraction?<><Check size={16}/>提取已核查</>:'确认提取符合原话'}</Button></div>
 <div className="review-card"><div className="review-top"><span className="step-dot">2</span><span className="pill orange">项目数据修订</span><span className="status">{review.data?'Choi 已确认':'由 Choi 确认'}</span></div><h2>更新数据，同时保留研究历史</h2><div className="value-change"><div><small>09.12 · v1 · 初步陈述</small><strong>610 <em>Ω·μm</em></strong></div><ArrowRight/><div><small>09.23 · v2 · {review.data?'当前有效':'待确认'}</small><strong>690 <em>Ω·μm</em></strong></div></div><p>Choi 说明旧数值来自旧版汇总表；同为 M09 / B 组 / n=5。更新后，计算降幅变为 15.9%。</p><button className="text-link" onClick={()=>source(2,3)}>查看纠正发言 / 09.23 / 18:42 ↗</button><div className="inline-warning">影响：月报中的 610、25.6% 和目标达成判断。旧会议转录保留，旧草稿需复核。</div>{!review.extraction&&<p className="muted">先完成第 1 步，确认原记录确实来自会议发言。</p>}{overrides['2-3']&&<p className="warning">来源转录已编辑，请在会议记录中还原后继续。</p>}<Button disabled={review.data||!review.extraction||actor!=='Choi'||!!overrides['2-3']} onClick={()=>confirm('data')}>{review.data?'✓ 已确认新版':actor!=='Choi'?'切换到 Choi 后确认':'确认 690，替代旧版本'}</Button></div>
 <div className="review-card"><div className="review-top"><span className="step-dot">3</span><span className="pill">项目决策</span><span className="status">{review.decision?'Park 已确认':'由 Park 确认'}</span></div><h2>75% 门槛，从什么时候开始生效？</h2><p>两组初筛通过率均至少 75%。该门槛在 9 月 23 日提出，不能追溯写成月初已有的标准。</p><button className="text-link" onClick={()=>source(2,0)}>来源：Park / 09.23 / 02:10 ↗</button><div className="actions"><Button disabled={review.decision||actor!=='Park'} onClick={()=>confirm('decision')}>{review.decision?'✓ 决策已确认':actor!=='Park'?'切换到 Park 后确认':'确认决策与生效日期'}</Button></div></div><Button onClick={()=>navigate('progress')}>查看项目进展与月报 <ArrowRight size={16}/></Button></section><aside><div className="side-card sticky"><h3>为什么分成三步？</h3><ol className="explain-list"><li><strong>听对了吗？</strong><p>核对原话与 AI 提取，避免把目标当结果。</p></li><li><strong>后来变了吗？</strong><p>数据负责人确认修订，旧版本退出当前调用。</p></li><li><strong>团队决定了吗？</strong><p>负责人确认决策，保留适用时间。</p></li></ol><p className="muted">模拟角色限制仅演示流程。生产版需要真实身份、权限与审计。</p>{audit.length>0&&<><h3>本次操作记录</h3>{audit.map((a,i)=><p className="audit" key={i}><Check size={14}/>{a}</p>)}</>}</div></aside></div></TabsContent>
 <TabsContent value="progress"><div className="page-heading"><div><div className="eyebrow">PROJECT MEMORY / SEPTEMBER</div><h1>让下一份报告，用上最新依据。</h1><p className="subtitle">信息从三次会议汇入，同步呈现状态、来源与变化。</p></div><Button variant="outline" onClick={()=>navigate('review')}>返回核查</Button></div><div className="metrics"><div className="metric"><span>月初目标</span><strong>20<small>%</small></strong><p>降低接触电阻 · 目标</p><button className="text-link" onClick={()=>source(0,0)}>09.02 · Park ↗</button></div><div className="metric"><span>B 组当前接触电阻</span><strong>{review.data?'690':'待核查'}<small>{review.data?' Ω·μm':''}</small></strong><p>{review.data?'n=5 · 经 Choi 确认':'610 与 690 冲突，暂停引用'}</p><button className="text-link" onClick={()=>source(2,3)}>09.23 · Choi ↗</button></div><div className="metric"><span>相对降幅</span><strong>{review.data?'15.9':'—'}<small>{review.data?'%':''}</small></strong><p>{review.data?'(820 − 690) / 820 · 未达目标':'等待数据确认后计算'}</p></div><div className="metric"><span>良率门槛</span><strong>{review.decision?'75':'待确认'}<small>{review.decision?'%':''}</small></strong><p>两组均须达到 · 09.23 起</p><button className="text-link" onClick={()=>source(2,0)}>09.23 · Park ↗</button></div></div>
 <div className="detail-grid"><section className="surface report-surface"><div className="section-head"><h2>九月进展摘要</h2><span className="pill">基于项目记忆</span></div><p>知序会主动查找相关会议；有争议的数据不会作为当前事实写入。</p><div className="actions"><Button disabled={!!overrides['2-3']} onClick={()=>{setDraft(makeReport(review));setDraftState(JSON.stringify(review))}}>生成最新进展摘要 <FileText size={16}/></Button>{draft&&<Button variant="outline" disabled={draftState!==JSON.stringify(review)||!!overrides['2-3']} onClick={exportDraft}>下载摘要</Button>}</div>{overrides['2-3']&&<div className="inline-warning">来源转录已编辑，当前指标与草稿需复核；还原预置片段后可继续本演示。</div>}{draft&&<div className="report" aria-live="polite"><small>{review.data&&review.decision?'基于已确认记录':'部分信息待确认'}</small>{draftState!==JSON.stringify(review)&&<div className="inline-warning">项目记忆已更新，这份草稿需重新生成。</div>}{draft.split('\n\n').map(p=><p key={p}>{p}</p>)}<div className="citations"><button onClick={()=>source(0,0)}>目标 / 09.02</button><button onClick={()=>source(2,3)}>数据修订 / 09.23</button><button onClick={()=>source(2,2)}>初筛结果 / 09.23</button><button onClick={()=>source(2,0)}>门槛 / 09.23</button></div></div>}<details className="old-draft"><summary>受影响的旧月报草稿 · 需复核</summary><p>“据初步数据，B 组为 610 Ω·μm，相对 A 组降低约 25.6%，超过 20% 目标。”</p><div className="inline-warning">预置历史草稿，依赖 09.12 初步数字；新会议提出纠正后已失效。保留原文供追溯，不静默改写。</div></details></section><aside><div className="side-card"><h3>准备下一次会议</h3><p>根据三次讨论，知序建议优先确认：</p><ul className="todo"><li>{review.data?'Choi：补齐原始数据文件和测试条件。':'Choi：确认 690 与 610 的修订关系。'}</li><li>{review.decision?'Lee：确认清洗对照实验安排。':'Park：确认 75% 门槛及适用时间。'}</li><li>Han：修订月报并补齐器件排除原因。</li><li>Wang：保留机制假设，不写为因果结论。</li></ul><p className="muted">任务来自会议陈述；未自动通知成员，也未假定任务已完成。</p></div><details className="side-card"><summary>项目记忆的版本轨迹</summary><p>09.02：目标 20%，与实测结果分开。</p><p>09.12：610 Ω·μm，初步陈述。</p><p>09.23：提出 690 修订，旧值停止用于当前报告。</p><p>{review.data?'Choi 已确认：690 为当前有效版本。':'当前：等待 Choi 确认修订。'}</p></details></aside></div></TabsContent>
 {notice&&<div className="feedback" role="status"><Check size={18}/>{notice}<button aria-label="关闭提示" onClick={()=>setNotice('')}>×</button></div>}
 </div></Tabs><footer><span>知序 · IBS 研究团队场景原型</span><span>来源可追溯 / 版本可纠正 / 判断有边界</span></footer></div>
}

