'use client';
import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import {
  transcript,
  versions,
  signature,
  saveTranscript,
  generateSummary,
} from '@/lib/transcripts';
import { meetings, people, timestamps } from '@/lib/scenario';
import type { State } from '@/lib/memory';
import { translate, type Locale } from '@/lib/i18n';
export function MeetingRecord({
  state,
  meeting,
  actor,
  language,
  onSave,
}: {
  state: State;
  meeting: number;
  actor: string;
  language: Locale;
  onSave: (s: State, message: string) => void;
}) {
  const en = language === 'en',
    t = (text: string) => translate(text, language);
  const [editor, setEditor] = useState<number | null>(null),
    [draft, setDraft] = useState(''),
    [error, setError] = useState('');
  const summary = state.meetingSummaries?.[meeting],
    stale = !!summary && summary.signature !== signature(state, meeting);
  useEffect(() => {
    if (!state.meetingSummaries?.[meeting])
      onSave(
        generateSummary(state, meeting, actor),
        en ? 'Meeting summary generated.' : '已生成会议摘要。',
      );
  }, [meeting]);
  const date = (value: string | null) =>
    value
      ? new Date(value).toLocaleString(en ? 'en-US' : 'zh-CN', {
          hour12: false,
        })
      : en
        ? 'Original record · time unavailable'
        : '原始记录 · 时间未记录';
  // Present source records in the selected language, including in the editable field.
  // An intentional edit is then saved as a new, traceable version in that language.
  function edit(i: number) {
    setEditor(i);
    setDraft(t(transcript(state, meeting, i)));
    setError('');
  }
  return (
    <Tabs defaultValue="summary">
      <TabsList variant="line">
        <TabsTrigger value="summary">{en ? 'Summary' : '摘要'}</TabsTrigger>
        <TabsTrigger value="transcript">
          {en ? 'Transcript' : '转录'}
        </TabsTrigger>
      </TabsList>
      <TabsContent value="summary">
        <div className="summary-meta">
          <div>
            {summary ? (
              <>
                <time dateTime={summary.generatedAt}>
                  {en ? 'Generated: ' : '生成于：'}
                  {date(summary.generatedAt)}
                </time>
                <small>
                  {en ? 'Generated by' : '生成人'} {summary.author}
                </small>
              </>
            ) : (
              <span>
                {en
                  ? 'No timestamped summary yet.'
                  : '尚未生成带时间戳的摘要。'}
              </span>
            )}
            {summary && (
              <strong className={stale ? 'summary-stale' : ''}>
                {stale
                  ? en
                    ? 'Outdated · transcript edited'
                    : '已过时 · 转录已修改'
                  : en
                    ? 'Up to date'
                    : '与当前转录一致'}
              </strong>
            )}
          </div>
          <Button
            onClick={() =>
              onSave(
                generateSummary(state, meeting, actor),
                en
                  ? 'Summary generated from the current transcript.'
                  : '已根据当前转录生成摘要。',
              )
            }
          >
            {summary
              ? en
                ? 'Regenerate summary'
                : '重新生成摘要'
              : en
                ? 'Generate summary'
                : '生成摘要'}
          </Button>
        </div>
        {summary ? (
          <>
            <p className="fine-print">
              {en
                ? 'Extractive demo: first two sentences per speaker. These are meeting statements, not verified conclusions.'
                : '摘录式演示：提取每位发言人的前两句话，仅代表会议陈述，不代表已核实结论。'}
            </p>
            {summary.lines.map((line, i) => (
              <div className="summary-line" key={i}>
                <strong>{line.speaker}</strong>
                <p>{t(line.text)}</p>
              </div>
            ))}
          </>
        ) : (
          <p className="fine-print">
            {en
              ? 'Generate a summary to record its creation time and source version.'
              : '生成摘要后会保留生成时间及来源版本。'}
          </p>
        )}
      </TabsContent>
      <TabsContent value="transcript">
        {meetings[meeting].speeches.map((_, i) => {
          const history = versions(state, meeting, i),
            latest = history.at(-1)!;
          return (
            <article className="transcript-row" key={i}>
              <span className="person-initial">{people[i].name[0]}</span>
              <div className="transcript-content">
                <div className="transcript-meta">
                  <strong>{people[i].name}</strong>
                  <span>{t(people[i].role)}</span>
                  <time>{timestamps[i]}</time>
                </div>
                <p>{t(transcript(state, meeting, i))}</p>
                <small className="transcript-version">
                  v{latest.version} · {latest.author} · {date(latest.at)}
                </small>
                <div className="compact-actions">
                  <Button variant="outline" onClick={() => edit(i)}>
                    {en ? 'Review & edit' : '核查与编辑'}
                  </Button>
                  <details className="transcript-history">
                    <summary>
                      {en ? 'Version history' : '版本记录'} ({history.length})
                    </summary>
                    {history
                      .slice()
                      .reverse()
                      .map((v) => (
                        <div
                          className="transcript-version-entry"
                          key={v.version}
                        >
                          <strong>
                            v{v.version} · {v.author}
                          </strong>
                          <small>{date(v.at)}</small>
                          <p>{t(v.text)}</p>
                        </div>
                      ))}
                  </details>
                </div>
              </div>
            </article>
          );
        })}
      </TabsContent>
      <Dialog
        open={editor !== null}
        onOpenChange={(open) => {
          if (!open) setEditor(null);
        }}
      >
        <DialogContent className="transcript-editor">
          <DialogHeader>
            <DialogTitle>
              {en ? 'Review & edit transcript' : '核查与编辑转录'} ·{' '}
              {editor !== null ? people[editor].name : ''}
            </DialogTitle>
            <DialogDescription>
              {en
                ? `Saved as a new version by ${actor}. Previous versions remain available.`
                : `以 ${actor} 身份保存为新版本，保留所有历史版本。`}
            </DialogDescription>
          </DialogHeader>
          <Textarea
            aria-label={en ? 'Transcript text' : '转录内容'}
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
          />
          <div className="compact-actions">
            <Button
              disabled={
                !draft.trim() ||
                editor === null ||
                draft.trim() === t(transcript(state, meeting, editor))
              }
              onClick={() => {
                try {
                  if (editor !== null) {
                    onSave(
                      saveTranscript(state, meeting, editor, draft, actor),
                      en
                        ? 'New transcript version saved. Related summaries may be outdated.'
                        : '已保存新版本，相关摘要可能已过时。',
                    );
                    setEditor(null);
                  }
                } catch (e) {
                  setError((e as Error).message);
                }
              }}
            >
              {en ? 'Save new version' : '保存新版本'}
            </Button>
            <Button variant="outline" onClick={() => setEditor(null)}>
              {en ? 'Cancel' : '取消'}
            </Button>
          </div>
          {error && <p role="alert">{t(error)}</p>}
        </DialogContent>
      </Dialog>
    </Tabs>
  );
}
