'use client';
import {ProjectPicker} from '@/components/project-picker';
import {useState,type ReactNode} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuRadioGroup,DropdownMenuRadioItem} from '@/components/ui/dropdown-menu';
import {LanguageSwitch} from '@/components/language';
import type {Locale} from '@/lib/i18n';
import {people} from '@/lib/scenario';
import {LayoutDashboard,BookOpen,Database,MessageSquare,ChevronDown,Mic} from 'lucide-react';
type Props={language:Locale;onLanguage:(v:Locale)=>void;actor:string;onActor:(v:string)=>void;project:string;view:string;onView:(v:string)=>void;children:ReactNode;pending?:number;onRecord?:()=>void;recording?:boolean};
const items=[['overview','Overview','项目概览',LayoutDashboard],['meetings','Meetings','会议',BookOpen],['memory','Memory','项目记忆',Database],['assistant','AI Assistant','AI 助手',MessageSquare]] as const;
function Navigation(p:Props){const {setOpenMobile}=useSidebar();const en=p.language==='en';return <Sidebar className="workspace-sidebar"><SidebarHeader><div className="sidebar-brand-row"><a href="/" className="demo-brand"><span>z.</span></a><a className="demo-guide" href="/docs">Guide</a></div><ProjectPicker name={p.project} en={en}/></SidebarHeader><SidebarContent><SidebarMenu>{items.map(([id,label,zh,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton isActive={p.view===id} onClick={()=>{p.onView(id);setOpenMobile(false)}}><Icon size={19} strokeWidth={2.3}/><span>{en?label:zh}</span>{id==='memory'&&!!p.pending&&<small className="workspace-count">{p.pending}</small>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter className="demo-header"><button className="workspace-record" onClick={()=>{p.onRecord?.();setOpenMobile(false)}}><span className="cartoon-voice" aria-hidden="true"><span className="cartoon-voice-core"><span className="voice-wave"><i/><i/><i/><i/></span></span></span><span>{p.recording?(en?"Recording · Open":"记录中 · 查看"):(en?"Start AI recording":"启动 AI 记录")}</span></button><div className="sidebar-account-row"><LanguageSwitch language={p.language} onChange={p.onLanguage}/><DropdownMenu><DropdownMenuTrigger className="demo-user-trigger"><span>{p.actor}</span><ChevronDown size={15}/></DropdownMenuTrigger><DropdownMenuContent className="demo-user-menu workspace-user-menu" align="start"><DropdownMenuRadioGroup value={p.actor} onValueChange={v=>p.onActor(String(v))}>{people.map(person=><DropdownMenuRadioItem className="demo-user-item" key={person.name} value={person.name}>{person.name}</DropdownMenuRadioItem>)}</DropdownMenuRadioGroup></DropdownMenuContent></DropdownMenu></div></SidebarFooter></Sidebar>}
export function ProjectShell(p:Props){const [open,setOpen]=useState(false),[consent,setConsent]=useState(false),[recording,setRecording]=useState(false);const en=p.language==='en';return <SidebarProvider className="workspace-shell"><Navigation {...p} recording={p.recording??recording} onRecord={p.onRecord??(()=>setOpen(true))}/><div className="workspace-body"><header className="workspace-top"><SidebarTrigger/><span>{items.find(i=>i[0]===p.view)?.[p.language==='en'?1:2]}</span></header>{p.children}</div><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{en?'AI meeting recording':'AI 会议记录'}</DialogTitle><DialogDescription>{en?'Simulated recording. Your microphone is not accessed.':'模拟会议记录，不访问麦克风。'}</DialogDescription></DialogHeader><label className="checkbox-line"><Checkbox checked={consent} disabled={recording} onCheckedChange={v=>setConsent(Boolean(v))}/>{en?'All participants have agreed to recording.':'所有参与者已知情同意录制。'}</label><p role="status">{recording?(en?'Simulated recording in progress…':'正在模拟记录…'):(en?'Ready to record.':'准备就绪。')}</p><Button disabled={!consent} onClick={()=>setRecording(!recording)}>{recording?(en?'Stop recording':'结束记录'):(en?'Start recording':'开始记录')}</Button><p className="fine-print">{en?'Speaker identification and transcripts are demonstrated in the IBS sample project.':'说话人识别与转录效果可在 IBS 示例项目中体验。'}</p></DialogContent></Dialog></SidebarProvider>}



