'use client';
import {ResizablePanelGroup,ResizablePanel,ResizableHandle} from '@/components/ui/resizable';
import type {PanelImperativeHandle} from 'react-resizable-panels';
import {useIsMobile} from '@/hooks/use-mobile';
import {ProjectPicker} from '@/components/project-picker';
import {useState,useRef,useEffect,type ReactNode} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuRadioGroup,DropdownMenuRadioItem} from '@/components/ui/dropdown-menu';
import {LanguageSwitch} from '@/components/language';
import type {Locale} from '@/lib/i18n';
import {people} from '@/lib/scenario';
import {sitePath} from '@/lib/site-path';
import {LayoutDashboard,BookOpen,Database,MessageSquare,ChevronDown,Mic,PanelLeft} from 'lucide-react';
type Props={language:Locale;onLanguage:(v:Locale)=>void;actor:string;onActor:(v:string)=>void;project:string;view:string;onView:(v:string)=>void;children:ReactNode;pending?:number;onRecord?:()=>void;recording?:boolean;desktop?:boolean};
const items=[['overview','Overview','项目概览',LayoutDashboard],['meetings','Meetings','会议',BookOpen],['memory','Memory','项目记忆',Database],['assistant','AI Assistant','AI 助手',MessageSquare]] as const;
function Navigation(p:Props){const {setOpenMobile}=useSidebar();const en=p.language==='en';return <Sidebar className="workspace-sidebar" collapsible={p.desktop?"none":"offcanvas"}><SidebarHeader><div className="sidebar-brand-row"><a href={sitePath('/')} className="demo-brand"><span>z.</span></a><a className="demo-guide" href={sitePath('/docs')}>Guide</a></div><ProjectPicker name={p.project} en={en}/></SidebarHeader><SidebarContent><SidebarMenu>{items.map(([id,label,zh,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton isActive={p.view===id} aria-current={p.view===id?"page":undefined} onClick={()=>{p.onView(id);setOpenMobile(false)}}><Icon size={19} strokeWidth={2.3}/><span>{en?label:zh}</span>{id==='memory'&&!!p.pending&&<small className="workspace-count">{p.pending}</small>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter className="demo-header"><button className="workspace-record" onClick={()=>{p.onRecord?.();setOpenMobile(false)}}><span className="simple-voice-orb" aria-hidden="true"><span/></span><span>{p.recording?(en?"Recording · Open":"记录中 · 查看"):(en?"Start AI recording":"启动 AI 记录")}</span></button><div className="sidebar-account-row"><LanguageSwitch language={p.language} onChange={p.onLanguage}/><DropdownMenu><DropdownMenuTrigger className="demo-user-trigger"><span>{p.actor}</span><ChevronDown size={15}/></DropdownMenuTrigger><DropdownMenuContent className="demo-user-menu workspace-user-menu" align="start"><DropdownMenuRadioGroup value={p.actor} onValueChange={v=>p.onActor(String(v))}>{people.map(person=><DropdownMenuRadioItem className="demo-user-item" key={person.name} value={person.name}>{person.name}</DropdownMenuRadioItem>)}</DropdownMenuRadioGroup></DropdownMenuContent></DropdownMenu></div></SidebarFooter></Sidebar>}
export function ProjectShell(p:Props){const [open,setOpen]=useState(false),[consent,setConsent]=useState(false),[recording,setRecording]=useState(false);const en=p.language==='en';return <SidebarProvider className="workspace-shell"><WorkspacePanes {...p} recording={p.recording??recording} onRecord={p.onRecord??(()=>setOpen(true))}/><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{en?'AI meeting recording':'AI 会议记录'}</DialogTitle><DialogDescription>{en?'Simulated recording. Your microphone is not accessed.':'模拟会议记录，不访问麦克风。'}</DialogDescription></DialogHeader><label className="checkbox-line"><Checkbox checked={consent} disabled={recording} onCheckedChange={v=>setConsent(Boolean(v))}/>{en?'All participants have agreed to recording.':'所有参与者已知情同意录制。'}</label><p role="status">{recording?(en?'Simulated recording in progress…':'正在模拟记录…'):(en?'Ready to record.':'准备就绪。')}</p><Button disabled={!consent} onClick={()=>setRecording(!recording)}>{recording?(en?'Stop recording':'结束记录'):(en?'Start recording':'开始记录')}</Button><p className="fine-print">{en?'Speaker identification and transcripts are demonstrated in the IBS sample project.':'说话人识别与转录效果可在 IBS 示例项目中体验。'}</p></DialogContent></Dialog></SidebarProvider>}






function WorkspacePanes(p:Props){const mobile=useIsMobile();const panel=useRef<PanelImperativeHandle|null>(null);const [collapsed,setCollapsed]=useState(false);const [dragging,setDragging]=useState(false);const [sidebarWidth,setSidebarWidth]=useState(230);useEffect(()=>{const end=()=>setDragging(false);window.addEventListener("pointerup",end);window.addEventListener("pointercancel",end);return()=>{window.removeEventListener("pointerup",end);window.removeEventListener("pointercancel",end)}},[]);const body=<div className="workspace-body"><header className="workspace-top">{mobile?<SidebarTrigger/>:<button type="button" className="workspace-toggle" aria-label={p.language==="en"?(collapsed?"Show sidebar":"Hide sidebar"):(collapsed?"展开侧栏":"收起侧栏")} aria-expanded={!collapsed} onClick={()=>{if(panel.current?.isCollapsed())panel.current.expand();else panel.current?.collapse()}}><PanelLeft size={19}/></button>}<span>{items.find(i=>i[0]===p.view)?.[p.language==='en'?1:2]}</span></header>{p.children}</div>;if(mobile)return <><Navigation {...p}/>{body}</>;return <ResizablePanelGroup orientation="horizontal" className="workspace-resizable" data-collapsed={collapsed} data-dragging={dragging} style={{"--sidebar-opacity":collapsed?0:Math.max(0,Math.min(1,(sidebarWidth-110)/120))} as React.CSSProperties}><ResizablePanel id="navigation" panelRef={panel} collapsible collapsedSize="0px" onResize={size=>{setCollapsed(size.inPixels<1);setSidebarWidth(size.inPixels)}} defaultSize="230px" minSize="210px" maxSize="360px" className="workspace-nav-panel"><Navigation {...p} desktop/></ResizablePanel><ResizableHandle onPointerEnter={e=>{delete e.currentTarget.dataset.released}} onPointerDown={e=>{setDragging(true);delete e.currentTarget.dataset.released}} onPointerUp={e=>{e.currentTarget.dataset.released="true";e.currentTarget.blur()}} className="workspace-resize-handle" aria-label={p.language==='en'?'Resize sidebar':'调整侧栏宽度'}/><ResizablePanel id="content" minSize="400px" className="workspace-content-panel">{body}</ResizablePanel></ResizablePanelGroup>}




