'use client';
import type {ReactNode} from 'react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuRadioGroup,DropdownMenuRadioItem} from '@/components/ui/dropdown-menu';
import {LanguageSwitch} from '@/components/language';
import type {Locale} from '@/lib/i18n';
import {people} from '@/lib/scenario';
import {LayoutDashboard,BookOpen,Database,MessageSquare,ChevronDown} from 'lucide-react';
type Props={language:Locale;onLanguage:(v:Locale)=>void;actor:string;onActor:(v:string)=>void;project:string;view:string;onView:(v:string)=>void;children:ReactNode;pending?:number};
const items=[['overview','Overview','项目概览',LayoutDashboard],['meetings','Meetings','会议',BookOpen],['memory','Memory','项目记忆',Database],['assistant','AI Assistant','AI 助手',MessageSquare]] as const;
function Navigation(p:Props){const {setOpenMobile}=useSidebar();const en=p.language==='en';return <Sidebar className="workspace-sidebar"><SidebarHeader><a href="/" className="demo-brand"><span>z.</span></a><DropdownMenu><DropdownMenuTrigger className="project-switch">{p.project}<ChevronDown size={15}/></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem render={<a href="/demo"/>}>{en?'Switch project':'切换项目'}</DropdownMenuItem><DropdownMenuItem render={<a href="/demo?create=1"/>}>{en?'Create new project':'创建新项目'}</DropdownMenuItem></DropdownMenuContent></DropdownMenu></SidebarHeader><SidebarContent><SidebarMenu>{items.map(([id,label,zh,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton isActive={p.view===id} onClick={()=>{p.onView(id);setOpenMobile(false)}}><Icon size={18}/><span>{en?label:zh}</span>{id==='memory'&&!!p.pending&&<small className="workspace-count">{p.pending}</small>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter className="demo-header"><a className="demo-guide" href="/docs">Guide</a><LanguageSwitch language={p.language} onChange={p.onLanguage}/><DropdownMenu><DropdownMenuTrigger className="demo-user-trigger"><span>{p.actor}</span><ChevronDown size={15}/></DropdownMenuTrigger><DropdownMenuContent className="demo-user-menu" align="start"><DropdownMenuRadioGroup value={p.actor} onValueChange={v=>p.onActor(String(v))}>{people.map(person=><DropdownMenuRadioItem className="demo-user-item" key={person.name} value={person.name}>{person.name}</DropdownMenuRadioItem>)}</DropdownMenuRadioGroup></DropdownMenuContent></DropdownMenu></SidebarFooter></Sidebar>}
export function ProjectShell(p:Props){return <SidebarProvider className="workspace-shell"><Navigation {...p}/><div className="workspace-body"><header className="workspace-top"><SidebarTrigger/><span>{items.find(i=>i[0]===p.view)?.[p.language==='en'?1:2]}</span></header>{p.children}</div></SidebarProvider>}
