import type {Chapter} from './manual';
export const chaptersEn:Chapter[]=[
{id:'start',group:'Getting started',title:'Meet Zhixu',intro:'Zhixu connects meetings, review and future tasks for small teams working on long-running research projects. Use this guide alongside the interactive demo, positioning slides and evaluation workbook.',sections:[
{title:'One complete workflow',steps:['Meetings: read the summaries and statements from all six members across three meetings.','Review in place: the responsible person checks important data and decisions against the source.','Research assistant: start a new conversation to draft a monthly report or prepare for the next meeting.','Response sources: inspect the memories used and correct errors directly.'],note:'This is a rule-based prototype with browser-local storage. Real recording, model extraction, identity verification and cross-device synchronization are not connected.'},
{title:'Four deliverables',columns:['Material','What it explains'],rows:[['Positioning slides','Who the product serves, the problem and criteria for product viability'],['This guide','How information is recorded, reviewed, recalled and corrected'],['Interactive demo','Cross-conversation memory and automatic recall within a task'],['Evaluation guide and workbook','Methods, records and proposed acceptance thresholds']]},
{title:'Suggested reading order',text:'Start with “The team and three meetings” and “Review and confirmation”. For the product mechanism, continue to recall, correction and team sharing. Use the evaluation guide when planning validation. The downloadable slides and workbook are currently the Chinese editions; the full web guide is available in both languages.'}]},
{id:'scenario',group:'Getting started',title:'The team and three meetings',intro:'The fictional IBS scenario studies contact resistance improvements and initial device screening in 2D semiconductors. All people, dates, meetings and research values are illustrative and do not represent real IBS results.',sections:[
{title:'Six participants',columns:['Member','Responsibility','Role in Zhixu'],rows:[['Park · Professor','Project lead','Confirms targets, decisions and effective dates'],['Kim · Researcher','Materials','Tracks materials, batches and conditions'],['Lee · Researcher','Devices','Reviews screening definitions and fabrication plans'],['Choi · Postdoc','Electrical testing','Reviews values, sample sizes and test conditions'],['Wang · Postdoc','Mechanisms','Distinguishes hypotheses from verified findings'],['Han · PhD student','Documentation','Organizes records and prepares reports']]},
{title:'What changes across meetings',columns:['Meeting','What happens','Memory treatment'],rows:[['Sep 2 · Planning','Target: ≥20% reduction; 12 devices in each group','Store a target, not an achieved result'],['Sep 12 · First round','A820 (n=6), B610 (n=5), preliminary values','Retain attribution and preliminary status'],['Sep 23 · Progress','B revised to 690; a new 75% screening threshold','Choi confirms data; Park confirms the threshold effective Sep 23']]},
{title:'Keep sample definitions separate',text:'Contact resistance: A820 Ω·μm (n=6), B690 Ω·μm (n=5). Screening: A10/12 and B8/12. B shows a 15.9% reduction relative to A, below the 20% target. Its screening pass rate is 66.7%, below the new 75% threshold. Screening counts and resistance extraction samples have different denominators.',note:'These calculations establish neither causality nor statistical significance. Missing test conditions must not be invented.'}]},
{id:'capture',group:'Meetings and memory',title:'Recording and transcription',intro:'One meeting has one shared record. A device account does not necessarily identify one speaker. This chapter describes the intended production design; the current demo only simulates settings and uses prepared transcripts.',sections:[
{title:'Multiple participants and devices',columns:['Format','Capture arrangement','Review needed'],rows:[['In person','One main recording device; others view and annotate; video is optional','Map separated voice segments to people'],['Online','Retain individual audio tracks and align timestamps','A shared device may contain several speakers'],['Hybrid','Combine room audio with remote tracks; remove echo and duplicate segments','Avoid counting one statement more than once']]},
{title:'Before recording',steps:['Explain what is recorded, the purpose, participants and access scope.','Obtain informed consent; offer video as a separate choice.','Ask participants to review uncertain identities or suspected shared devices.'],note:'Separating speakers is not the same as identifying them. Keep an uncertain label such as “Speaker 2” until reviewed; do not turn voice or video guesses into confirmed identities.'},
{title:'Make failures visible',text:'Show gaps when recording or transcription fails. Let participants check timestamped source text and speaker attribution. A summary must disclose incomplete evidence rather than inventing missing discussion.'}]},
{id:'confirm',group:'Meetings and memory',title:'Review and confirmation',intro:'Checking that the assistant captured the statement faithfully differs from confirming that a value is suitable as current project evidence. One review interaction can cover both checks while preserving their distinct meaning.',sections:[
{title:'Try it in the demo',steps:['Open the Sep 23 meeting or the pending-review section in the assistant.','Compare the candidate value of 690, units and sample sizes with Choi’s source statement.','Switch to Choi’s demo view and select “Confirm reviewed data”.','Switch to Park to confirm the 75% threshold and its effective date.','Generate a monthly report and inspect its memories and sources.'],note:'Role switching demonstrates responsibility, not authentication. Previous actions are retained in local storage, so some items may already be confirmed.'},
{title:'Automatic actions and human control',columns:['Stage','Assistant','User'],rows:[['Transcript and summary','Produces text, candidate fields and possible conflicts','Checks important values, identities and missing segments'],['Project memory','Stores candidates with sources','Responsible owner confirms key data and decisions'],['Task recall','Filters by permission, status and relevance; drafts with citations','Chooses whether to use or exclude the information'],['Personal notes','Keeps them private by default','Author explicitly shares or withdraws'],['External actions','Records an action item','Separately authorizes actions such as sending messages']]},
{title:'When a candidate cannot be confirmed',text:'Choose “Do not save” or leave the candidate pending. When a conflict is known, do not continue to present the old value as current. Owner confirmation does not automatically establish significance or causality.'}]},
{id:'memory',group:'Meetings and memory',title:'How project memory is stored',intro:'Source records preserve evidence, summaries support reading, and project memories support future tasks. They are separate layers with different responsibilities.',sections:[
{title:'Fields in a memory',columns:['Field','Purpose or example'],rows:[['Project, type and content','M09 / data / B-group resistance 690 Ω·μm'],['Source and attribution','Sep 23, Choi, 18:42 and the supporting statement'],['Measurement context','Unit, statistic, group, sample size, batch and test conditions'],['Review and status','Who checked it, who confirmed it and whether it is active'],['Time and version','Recorded time, effective time and replacement relationships'],['Access scope','Private to the author or available to authorized project members']]},
{title:'Prototype states',columns:['State','Future recall'],rows:[['Pending review','Excluded; owner review is needed'],['Active','Still subject to permission, project and relevance checks'],['Do not save','Excluded; the owner may reopen review'],['Forgotten','Excluded and removed from memory content; the source meeting remains']]},
{title:'Production extensions',text:'A production system also needs explicit disputed, superseded and withdrawn states, structured effective times, review history and field-level evidence. The prototype uses simplified states, version numbers and fixed scenario text.'},
{title:'Local persistence',text:'This browser stores memory and conversations across refreshes. Tabs on the same origin can observe updates, but devices do not synchronize. Clearing browser data removes these records. Cross-tab updates are not transactional concurrency control.'}]},
{id:'recall',group:'Future tasks',title:'Cross-conversation recall',intro:'Automatic recall means bringing relevant history into the task the user starts, without requiring them to find and paste each record. This demo does not send background notifications or external messages.',sections:[
{title:'Selection before generation',steps:['Check access: the current person must still be permitted to see the source and memory.','Check state: exclude rejected, forgotten, pending, conflicted or superseded records.','Check project and effective time: do not mix projects or apply a new decision retroactively.','Match the task: reports may need targets, data, decisions and actions; unrelated records stay out.','Draft with sources and explain which memories were used or skipped.'],note:'The prototype uses fixed rules for research-related tasks. Real semantic retrieval and model generation require separate evaluation after integration.'},
{title:'Different tasks, different context',columns:['Task','Relevant history','Important qualification'],rows:[['Draft an M09 monthly report','Current 690 value, 20% target, screening results and 75% decision','Keep units, sample sizes, effective dates and sources'],['Prepare the next meeting','Outstanding tasks, data gaps and mechanism hypotheses','A task is not complete without evidence; a hypothesis is not a result']]},
{title:'When evidence is insufficient',text:'State the gap or pending review instead of inventing a definite conclusion. Users may inspect sources, correct data or exclude a memory for this response. Cross-project reuse is a future capability that requires permission and experimental-context checks.'}]},
{id:'correction',group:'Future tasks',title:'Correction and version updates',intro:'A correction must affect future use while preserving what was actually said at the time.',sections:[
{title:'Two kinds of error',columns:['Error','Treatment'],rows:[['Transcription error: 690 was spoken but 610 was recorded','Correct the transcript, retain edit history, invalidate derived candidates and review extraction again'],['Data revision: 610 was actually stated, later corrected to 690','Keep the original statement, add the revised value and link the replacement; stop citing the old value as current']]},
{title:'Try the correction workflow',steps:['Open Choi’s source from the third meeting and edit the transcript.','Save to re-extract automatically. Unsupported wording produces an error and pauses use of the old value.','Choi checks and confirms the new candidate; future responses use that version.','The current response updates, while other affected historical responses require review.'],note:'In English, retain “The reviewed value is NUMBER Ω·μm”, B’s 5 valid samples and A at 820 with 6 valid samples. The Chinese equivalent is also supported. This is a conservative demo grammar, not a general extraction model.'},
{title:'Language and evidence',text:'The prepared scenario has a reviewed English translation. Switching language changes its presentation, not the underlying memory or version. The English editor supports the same sample correction. Custom wording is retained as entered rather than translated by a live model.'},
{title:'Derived content',text:'Production reports need dependencies on memory IDs and versions. Recheck versions before generation and flag affected reports after changes. Correction notifications should reach only affected people who still have access. Downloaded reports cannot be remotely retracted.'}]},
{id:'sharing',group:'Future tasks',title:'Team sharing and forgetting',intro:'Sharing a memory does not turn it into a team consensus or grant permanent access. Keep authorship, scope and a withdrawal path.',sections:[
{title:'Try sharing in the demo',steps:['Switch to Wang and open the personal research note in project memory.','Explicitly share it with the M09 team before other roles can use it.','Withdraw sharing: other roles stop using it and affected past responses must be regenerated.','Owners may forget their memory; other members may exclude it from a response.'],note:'These are front-end demonstrations. Anyone using this browser can switch roles. This is not a system for storing real confidential data.'},
{title:'Three different actions',columns:['Action','Effect','What remains'],rows:[['Exclude for now','Omit the item from the current response','Memory, source and history'],['Forget project memory','Remove memory content and exclude it from future automatic recall','Original meeting; explicit extraction and confirmation are needed to restore it'],['Delete source material (future)','Apply the promised deletion to source, index and caches','Only essential audit metadata; define backup retention explicitly']]},
{title:'Additional team risks',columns:['Risk','Production mechanism'],rows:[['Personal view becomes a supposed consensus','Retain author and hypothesis status'],['Revoked users can still retrieve data','Check permission server-side at retrieval, generation and citation'],['A report exposes a restricted source','Inherit the strictest source access scope'],['Concurrent edits overwrite corrections','Use version-conditional writes and transactions'],['Documents contain fake instructions','Treat content as evidence, not authorization to share or act']]},
{title:'Notification boundary',text:'An action item does not mean a message was sent or a task completed. Revoking access does not retrieve exported files; production workflows must explain how recipients should handle affected materials.'}]},
{id:'evaluation',group:'Evaluation and delivery',title:'Evaluation guide',intro:'Evaluate three layers separately: workflow correctness, model and permission reliability, and practical user value. The workbook contains 20 test cases and room for 20 participants. Actual experiment inputs are blank.',sections:[
{title:'Layer 1: prototype workflow',text:'Run P01–P12 for persistence, owner confirmation, pending-data isolation, corrected citations, traceability, rejection, forgetting, sharing and project isolation. Record steps, observations, evidence, reviewer and date. Automated logic tests do not substitute for browser interactions or real model evaluations.'},
{title:'Layer 2: accuracy and safety after integration',columns:['Metric','Scoring unit','Proposed threshold'],rows:[['Values and units','Value, unit and sample definition must all match the gold standard','≥98%; at least 120 units'],['Confirmed memory accuracy','Content, attribution, state and effective time are all correct','≥95%; at least 120 units'],['Source support','Directly supported factual claims / all checkable claims','≥98%; at least 120 claims'],['Correction propagation','Queries that wrongly treat a superseded value as current','At least 100; zero observed errors'],['Permission and deletion','Unauthorized or improperly retained content in context/output','At least 100 each; zero observed errors']]},
{title:'Dataset and annotation',text:'Create at least 120 multi-meeting trajectories. Split development and held-out data by project to avoid leakage. Two annotators independently label source text, identity, fields, state and conclusions; a third resolves disagreements. Report transcription, speaker separation, identity and field accuracy separately for in-person, online, hybrid and shared-device settings.',note:'Use varied testing units rather than repeating one question. Report sample sizes and 95% confidence intervals. Zero errors in 100 trials still gives a one-sided 95% risk upper bound of about 2.95%. The workbook calculates that bound and the Wilson lower bound for accuracy.'},
{title:'Layer 3: a 12–20 participant crossover pilot',steps:['Recruit research workers and preregister tasks, scoring and thresholds.','A: ordinary transcript; B: single-meeting AI summary; C: Zhixu memory. Keep the model and evidence scope consistent.','Use equivalent report or meeting-preparation tasks with randomized orders such as ABC or CBA to reduce practice effects.','Include lookup, review, waiting and revision in task time. Two reviewers unaware of the condition independently score quality.','Compute each participant’s (B time − C time) / B time, then take the median. Ask whether each reminder was useful and whether it was disruptive.'],note:'B versus C is the main paired comparison; A is a reference. Quality is scored out of 5: factual accuracy 2, verifiable sources 1, time/sample definitions 1 and task completion 1. Retain evidence of wrongly accepted claims, review time and role-related waiting.'},
{title:'Proposed pilot gates',columns:['Metric','Threshold'],rows:[['Complete participant pairs','At least 12 unique participants'],['Median paired time saving','At least 20% relative to B'],['Mean quality change','C−B no worse than −0.2 out of 5'],['Reminder usefulness','Useful reminders / all reminders ≥70%'],['Disruption','Median disruptive reminders ≤1 per task']]},
{title:'Decision rules',text:'Pause and repair after unauthorized disclosure, use after deletion or use of superseded data as current. If information is correct but the value is insufficient, reduce memory scope or use on-demand retrieval. Expand the pilot only after meeting the proposed gates. A pilot is directional evidence; a larger study needs variance-based sample planning, order-effect analysis and confidence intervals.'},
{title:'Using the workbook',text:'The downloadable workbook is in Chinese. Read the test cases, enter observations and evidence into blue input cells, and record paired user tasks. The summary calculates statuses. Blank inputs, small samples, missing evidence and invalid entries do not count as passes. Retain separate records for each run instead of overwriting failures.'}]},
{id:'status',group:'Evaluation and delivery',title:'Capabilities and evidence',intro:'An interactive prototype, automated checks and real experiments provide different kinds of evidence. These are the boundaries of the current delivery.',sections:[
{title:'What is available',columns:['Capability','Status','Meaning'],rows:[['Three meetings and 18 statements','Interactive sample','Fictional scripts, not real recordings'],['Review, role rules, citations and correction','Interactive sample','Fixed rules for the prepared scenario'],['Persistence, rejection, forgetting and sharing','Interactive sample','Stored in this browser'],['Chinese and English interface','Available','Prepared scenario and guide translations; no live translation service'],['Scenario and memory logic tests','Automated checks','Not proof of browser interaction or model accuracy'],['Real model and recording','Not integrated','Requires separate testing'],['Server authorization, cloud sync and deletion','Not integrated','Role selection does not prove secure identity'],['User-value study','Not run','Targets such as 20% time saving are unverified']]},
{title:'Reviewing the project',text:'Try correction and cross-conversation recall, then inspect the guide’s confirmation boundaries. Use the positioning slides for the product rationale and the evaluation guide and workbook for validation plans. Downloadable slides and workbook remain the Chinese editions.'}]}
];
